-- Sudu Delivery: everything added since the first setup.
--
-- Safe to run more than once, and safe to run on a database that already has
-- some of it. Run this instead of setup.sql when the Supabase SQL editor
-- deadlocks on the storage policy: nothing here touches storage.

-- Everyone named in a group order, with the number to call when the food
-- lands. Without this a one-payer group knew the names on the bags but had no
-- way to reach the people they belong to.
create table if not exists group_members (
  id         uuid primary key default gen_random_uuid(),
  group_id   uuid not null references order_groups(id) on delete cascade,
  name       text not null,
  phone      text not null default '',
  hostel     text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists group_members_group_idx on group_members (group_id);
alter table group_members enable row level security;

-- The card link generated by hand, kept so it can be sent again.
alter table orders add column if not exists payment_link text;

-- A short number a person can say out loud.
create sequence if not exists order_no_seq start 1001;
alter table orders add column if not exists order_no bigint;
alter table orders alter column order_no set default nextval('order_no_seq');
update orders set order_no = nextval('order_no_seq') where order_no is null;
create unique index if not exists orders_order_no_idx on orders (order_no);

-- Editable message templates, and the line a paid customer reads.
alter table settings add column if not exists msg_confirmed text not null default '';
alter table settings add column if not exists msg_payment   text not null default '';
alter table settings add column if not exists msg_card      text not null default '';
alter table settings add column if not exists msg_pin       text not null default '';
alter table settings add column if not exists msg_ready     text not null default '';
alter table settings add column if not exists msg_late      text not null default '';
alter table settings add column if not exists paid_note     text not null default '';

-- What a run actually costs to make: fuel, whoever drove, and anything else
-- bought on the night. Without these the sheet could only say what was left
-- before those, which is not profit.
alter table batches add column if not exists fuel_cost   int not null default 0;
alter table batches add column if not exists driver_cost int not null default 0;
alter table batches add column if not exists other_cost  int not null default 0;
alter table batches add column if not exists cost_note   text not null default '';

-- The delivery price list, so it can be changed without a deploy.
alter table settings add column if not exists fee_bands text not null default '';

-- The blocks food is delivered to. Typed by hand, a hostel is misspelt every
-- other order and the run sheet cannot be sorted by it.
create table if not exists hostels (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  note       text not null default '',
  active     boolean not null default true,
  sort_order int not null default 100,
  created_at timestamptz not null default now()
);
alter table hostels enable row level security;

-- What the customer asked for on this order, and what the admin wants
-- remembered about it. Kept apart: one is theirs, one is yours.
alter table orders    add column if not exists customer_note text not null default '';
alter table orders    add column if not exists admin_note    text not null default '';
-- Anything worth remembering about a person across all their orders.
alter table customers add column if not exists admin_note    text not null default '';

-- A cart as it stood at checkout, kept so an order that never happened can be
-- followed up. Written only once a phone number is typed, because before that
-- there is nobody to follow up with.
create table if not exists carts (
  id            uuid primary key default gen_random_uuid(),
  phone         text not null,
  name          text not null default '',
  hostel        text not null default '',
  batch_id      uuid references batches(id) on delete set null,
  items         int not null default 0,
  value         int not null default 0,
  /** What was in it, as plain text, so admin can read it without a join. */
  summary       text not null default '',
  /** Set when an order from this number lands in the same run. */
  converted_at  timestamptz,
  /** Set when the admins have been told about it, so they are told once. */
  alerted_at    timestamptz,
  /** Set when the admin has dealt with it, however that went. */
  handled_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (phone, batch_id)
);
create index if not exists carts_updated_idx on carts (updated_at desc);
alter table carts enable row level security;

-- Who to email when something needs a person: one address per line.
alter table settings add column if not exists admin_emails text not null default '';
-- How long a cart sits untouched before it counts as abandoned.
alter table settings add column if not exists abandon_minutes int not null default 45;

-- Why a cart was closed, once it has been chased.
alter table carts add column if not exists handled_reason text not null default '';

-- What customers are told about when a run lands, per slot. It was fixed in
-- code, so moving the afternoon run half an hour meant a deploy.
alter table settings add column if not exists window_afternoon text not null default '';
alter table settings add column if not exists window_night     text not null default '';

-- How far ahead a customer can order.
alter table settings add column if not exists order_horizon_days int not null default 7;

-- The week's runs, as a schedule rather than a constant in the code. Each row
-- is one run on one weekday: when ordering closes, and when it lands.
create table if not exists run_schedule (
  id          uuid primary key default gen_random_uuid(),
  /** 0 = Sunday, through 6 = Saturday, as JavaScript counts them. */
  weekday     int not null check (weekday between 0 and 6),
  slot        batch_slot not null,
  /** Lagos time. Ordering closes at this time on that day. */
  cut_off     time not null,
  /** What customers are told about when it lands. */
  window_text text not null default '',
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  unique (weekday, slot)
);
alter table run_schedule enable row level security;

-- No days are seeded here. This file is run on a database that is already
-- working, and a week with nothing in it is a decision somebody made in
-- admin. Seeding Friday back into an empty table is how a day you deleted
-- reappeared the next time you ran this. A brand new database gets its
-- Friday from setup.sql.

-- A promoter signs in with their code and a four-digit PIN, the same way a
-- customer opens their order history.
alter table promoters add column if not exists pin text not null default '';

-- Where to send their money, kept by them so nobody retypes it.
alter table promoters add column if not exists bank_name text not null default '';
alter table promoters add column if not exists bank_account_name text not null default '';
alter table promoters add column if not exists bank_account_number text not null default '';

-- The promoter writes their own nudge to somebody who ordered and did not
-- pay. Empty means the standard wording.
alter table promoters add column if not exists nudge_template text not null default '';

-- A payout is recorded by you and confirmed by them, so both ends agree.
alter table promoter_payouts add column if not exists confirmed_at timestamptz;
alter table promoter_payouts add column if not exists batch_id uuid references batches(id) on delete set null;


-- What has actually been handed over, so "owed" means what is still owed
-- rather than everything ever earned.
create table if not exists promoter_payouts (
  id            uuid primary key default gen_random_uuid(),
  promoter_code text not null references promoters(code) on delete cascade,
  amount        int not null check (amount > 0),
  note          text not null default '',
  paid_at       timestamptz not null default now()
);
create index if not exists promoter_payouts_code_idx
  on promoter_payouts (promoter_code, paid_at desc);
alter table promoter_payouts enable row level security;

-- Anyone without a PIN gets one, so an existing promoter can sign in.
update promoters
set pin = lpad((floor(random() * 10000))::int::text, 4, '0')
where pin = '';

-- Every order counts for this promoter, ref code or not.
alter table settings add column if not exists default_promoter_code text not null default '';

-- Discount codes, which have nothing to do with the promoter. They are a thing
-- to put in a WhatsApp group on a slow Wednesday: "use FREEDEL and delivery is
-- on us tonight".
create table if not exists coupons (
  code             text primary key,
  /** "delivery" comes off the fee and never more than it; "order" off the total. */
  applies_to       text not null default 'delivery'
                     check (applies_to in ('delivery', 'order')),
  amount           int not null check (amount > 0),
  /** A note to yourself about why it exists. */
  note             text not null default '',
  active           boolean not null default true,
  /** Optional limits: after this date, or after this many uses, it stops. */
  expires_at       timestamptz,
  max_uses         int,
  used             int not null default 0,
  first_order_only boolean not null default false,
  created_at       timestamptz not null default now()
);
alter table coupons enable row level security;

-- What a coupon actually took off an order, for the books.
alter table orders add column if not exists coupon_code text;

-- Which runs a code works on. A code is usually for one night: the Wednesday
-- that needs filling, not the next fortnight. With no rows here it works on
-- any run, which is the occasional code that runs all term.
create table if not exists coupon_runs (
  coupon_code text not null references coupons(code) on delete cascade,
  batch_id    uuid not null references batches(id) on delete cascade,
  primary key (coupon_code, batch_id)
);
create index if not exists coupon_runs_batch_idx on coupon_runs (batch_id);
alter table coupon_runs enable row level security;

-- The slider on the home page, written and illustrated in admin rather than
-- assembled from whatever restaurants happen to exist.
create table if not exists slides (
  id         uuid primary key default gen_random_uuid(),
  headline   text not null,
  body       text not null default '',
  image_url  text not null default '',
  /** Where the button goes, and what it says. Blank hides the button. */
  link_url   text not null default '',
  link_text  text not null default '',
  active     boolean not null default true,
  sort_order int not null default 100,
  created_at timestamptz not null default now()
);
alter table slides enable row level security;

-- The line under the name in the header.
alter table settings add column if not exists tagline text not null default '';
alter table settings add column if not exists hide_promoter_link text not null default '';
alter table settings add column if not exists hide_footer text not null default '';

-- The slider the home page builds for itself when there are no slides.
alter table settings add column if not exists auto_headline text not null default '';
alter table settings add column if not exists auto_lines text not null default '';

-- The strip along the top of every page, and a code to announce beside it.
alter table settings add column if not exists ribbon_text text not null default '';
alter table settings add column if not exists offer_code text not null default '';

-- More than one account to pay into. A customer paying from the same bank
-- gets an instant transfer and no fee, which is worth a choice.
create table if not exists bank_accounts (
  id             uuid primary key default gen_random_uuid(),
  bank_name      text not null,
  account_name   text not null default '',
  account_number text not null,
  sort_order     int not null default 100,
  active         boolean not null default true,
  created_at     timestamptz not null default now(),
  unique (bank_name, account_number)
);
alter table bank_accounts enable row level security;

-- What the shop is being looked at with. Anonymous: a random id kept in the
-- browser, the path, and where the visit came from. No name, no number, and
-- nothing that ties a view to a customer.
create table if not exists page_views (
  id         bigserial primary key,
  path       text not null,
  visitor    text not null,
  referrer   text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists page_views_created_idx on page_views (created_at desc);
create index if not exists page_views_visitor_idx on page_views (visitor, created_at desc);
alter table page_views enable row level security;

-- The account already in settings becomes the first one on the list, so
-- nothing changes for anybody the day this runs. Only into an empty table.
insert into bank_accounts (bank_name, account_name, account_number, sort_order)
select s.bank_name, s.bank_account_name, s.bank_account_number, 10
from settings s
where s.id
  and s.bank_name <> ''
  and s.bank_account_number <> ''
  and not exists (select 1 from bank_accounts);

-- Supabase caches the schema; this makes the new columns visible immediately.
notify pgrst, 'reload schema';
