-- Sudu Delivery: everything added since the first setup.
--
-- Safe to run more than once, and safe to run on a database that already has
-- some of it. Run this instead of setup.sql when the Supabase SQL editor
-- deadlocks on the storage policy: nothing here touches storage.

-- Everyone named in a group order, with the number to call when the food
-- lands. Without this a one-payer group knew the names on the bags but had no
-- way to reach the people they belong to.
create table if not exists group_members (
  id         uuid primary key default gen_random_uuid(),
  group_id   uuid not null references order_groups(id) on delete cascade,
  name       text not null,
  phone      text not null default '',
  hostel     text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists group_members_group_idx on group_members (group_id);
alter table group_members enable row level security;

-- The card link generated by hand, kept so it can be sent again.
alter table orders add column if not exists payment_link text;

-- A short number a person can say out loud.
create sequence if not exists order_no_seq start 1001;
alter table orders add column if not exists order_no bigint;
alter table orders alter column order_no set default nextval('order_no_seq');
update orders set order_no = nextval('order_no_seq') where order_no is null;
create unique index if not exists orders_order_no_idx on orders (order_no);

-- Editable message templates, and the line a paid customer reads.
alter table settings add column if not exists msg_confirmed text not null default '';
alter table settings add column if not exists msg_payment   text not null default '';
alter table settings add column if not exists msg_card      text not null default '';
alter table settings add column if not exists msg_pin       text not null default '';
alter table settings add column if not exists msg_ready     text not null default '';
alter table settings add column if not exists msg_late      text not null default '';
alter table settings add column if not exists paid_note     text not null default '';

-- What a run actually costs to make: fuel, whoever drove, and anything else
-- bought on the night. Without these the sheet could only say what was left
-- before those, which is not profit.
alter table batches add column if not exists fuel_cost   int not null default 0;
alter table batches add column if not exists driver_cost int not null default 0;
alter table batches add column if not exists other_cost  int not null default 0;
alter table batches add column if not exists cost_note   text not null default '';

-- Set when the closing reminder for a run has gone out, so it goes once.
alter table batches add column if not exists closing_notified_at timestamptz;

-- The delivery price list, so it can be changed without a deploy.
alter table settings add column if not exists fee_bands text not null default '';

-- The blocks food is delivered to. Typed by hand, a hostel is misspelt every
-- other order and the run sheet cannot be sorted by it.
create table if not exists hostels (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  note       text not null default '',
  active     boolean not null default true,
  sort_order int not null default 100,
  created_at timestamptz not null default now()
);
alter table hostels enable row level security;

-- What the customer asked for on this order, and what the admin wants
-- remembered about it. Kept apart: one is theirs, one is yours.
alter table orders    add column if not exists customer_note text not null default '';
alter table orders    add column if not exists admin_note    text not null default '';
-- Anything worth remembering about a person across all their orders.
alter table customers add column if not exists admin_note    text not null default '';

-- A cart as it stood at checkout, kept so an order that never happened can be
-- followed up. Written only once a phone number is typed, because before that
-- there is nobody to follow up with.
create table if not exists carts (
  id            uuid primary key default gen_random_uuid(),
  phone         text not null,
  name          text not null default '',
  hostel        text not null default '',
  batch_id      uuid references batches(id) on delete set null,
  items         int not null default 0,
  value         int not null default 0,
  /** What was in it, as plain text, so admin can read it without a join. */
  summary       text not null default '',
  /** Set when an order from this number lands in the same run. */
  converted_at  timestamptz,
  /** Set when the admins have been told about it, so they are told once. */
  alerted_at    timestamptz,
  /** Set when the admin has dealt with it, however that went. */
  handled_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (phone, batch_id)
);
create index if not exists carts_updated_idx on carts (updated_at desc);
alter table carts enable row level security;

-- Who to email when something needs a person: one address per line.
alter table settings add column if not exists admin_emails text not null default '';
-- How long a cart sits untouched before it counts as abandoned.
alter table settings add column if not exists abandon_minutes int not null default 45;

-- Why a cart was closed, once it has been chased.
alter table carts add column if not exists handled_reason text not null default '';

-- What customers are told about when a run lands, per slot. It was fixed in
-- code, so moving the afternoon run half an hour meant a deploy.
alter table settings add column if not exists window_afternoon text not null default '';
alter table settings add column if not exists window_night     text not null default '';

-- How far ahead a customer can order.
alter table settings add column if not exists order_horizon_days int not null default 7;

-- The week's runs, as a schedule rather than a constant in the code. Each row
-- is one run on one weekday: when ordering closes, and when it lands.
create table if not exists run_schedule (
  id          uuid primary key default gen_random_uuid(),
  /** 0 = Sunday, through 6 = Saturday, as JavaScript counts them. */
  weekday     int not null check (weekday between 0 and 6),
  slot        batch_slot not null,
  /** Lagos time. Ordering closes at this time on that day. */
  cut_off     time not null,
  /** What customers are told about when it lands. */
  window_text text not null default '',
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  unique (weekday, slot)
);
alter table run_schedule enable row level security;

-- No days are seeded here. This file is run on a database that is already
-- working, and a week with nothing in it is a decision somebody made in
-- admin. Seeding Friday back into an empty table is how a day you deleted
-- reappeared the next time you ran this. A brand new database gets its
-- Friday from setup.sql.

-- A promoter signs in with their code and a four-digit PIN, the same way a
-- customer opens their order history.
alter table promoters add column if not exists pin text not null default '';

-- Where to send their money, kept by them so nobody retypes it.
alter table promoters add column if not exists bank_name text not null default '';
alter table promoters add column if not exists bank_account_name text not null default '';
alter table promoters add column if not exists bank_account_number text not null default '';

-- The promoter writes their own nudge to somebody who ordered and did not
-- pay. Empty means the standard wording.
alter table promoters add column if not exists nudge_template text not null default '';

-- What has actually been handed over, so "owed" means what is still owed
-- rather than everything ever earned.
create table if not exists promoter_payouts (
  id            uuid primary key default gen_random_uuid(),
  promoter_code text not null references promoters(code) on delete cascade,
  amount        int not null check (amount > 0),
  note          text not null default '',
  paid_at       timestamptz not null default now()
);
create index if not exists promoter_payouts_code_idx
  on promoter_payouts (promoter_code, paid_at desc);
alter table promoter_payouts enable row level security;

-- A payout is recorded by you and confirmed by them, so both ends agree.
-- These sit after the table is made, not before it: altering something that
-- does not exist yet stops the whole file on a database that has never had a
-- payout in it.
alter table promoter_payouts add column if not exists confirmed_at timestamptz;
alter table promoter_payouts add column if not exists batch_id uuid references batches(id) on delete set null;

-- Anyone without a PIN gets one, so an existing promoter can sign in.
update promoters
set pin = lpad((floor(random() * 10000))::int::text, 4, '0')
where pin = '';

-- Every order counts for this promoter, ref code or not.
alter table settings add column if not exists default_promoter_code text not null default '';

-- Discount codes, which have nothing to do with the promoter. They are a thing
-- to put in a WhatsApp group on a slow Wednesday: "use FREEDEL and delivery is
-- on us tonight".
create table if not exists coupons (
  code             text primary key,
  /** "delivery" comes off the fee and never more than it; "order" off the total. */
  applies_to       text not null default 'delivery'
                     check (applies_to in ('delivery', 'order')),
  amount           int not null check (amount > 0),
  /** A note to yourself about why it exists. */
  note             text not null default '',
  active           boolean not null default true,
  /** Optional limits: after this date, or after this many uses, it stops. */
  expires_at       timestamptz,
  max_uses         int,
  used             int not null default 0,
  first_order_only boolean not null default false,
  created_at       timestamptz not null default now()
);
alter table coupons enable row level security;

-- What a coupon actually took off an order, for the books.
alter table orders add column if not exists coupon_code text;

-- Which runs a code works on. A code is usually for one night: the Wednesday
-- that needs filling, not the next fortnight. With no rows here it works on
-- any run, which is the occasional code that runs all term.
create table if not exists coupon_runs (
  coupon_code text not null references coupons(code) on delete cascade,
  batch_id    uuid not null references batches(id) on delete cascade,
  primary key (coupon_code, batch_id)
);
create index if not exists coupon_runs_batch_idx on coupon_runs (batch_id);
alter table coupon_runs enable row level security;

-- The slider on the home page, written and illustrated in admin rather than
-- assembled from whatever restaurants happen to exist.
create table if not exists slides (
  id         uuid primary key default gen_random_uuid(),
  headline   text not null,
  body       text not null default '',
  image_url  text not null default '',
  /** Where the button goes, and what it says. Blank hides the button. */
  link_url   text not null default '',
  link_text  text not null default '',
  active     boolean not null default true,
  sort_order int not null default 100,
  created_at timestamptz not null default now()
);
alter table slides enable row level security;

-- The line under the name in the header.
alter table settings add column if not exists tagline text not null default '';
alter table settings add column if not exists hide_promoter_link text not null default '';
alter table settings add column if not exists hide_footer text not null default '';

-- The slider the home page builds for itself when there are no slides.
alter table settings add column if not exists auto_headline text not null default '';
alter table settings add column if not exists auto_lines text not null default '';

-- The strip along the top of every page, and a code to announce beside it.
alter table settings add column if not exists ribbon_text text not null default '';
alter table settings add column if not exists offer_code text not null default '';

-- More than one account to pay into. A customer paying from the same bank
-- gets an instant transfer and no fee, which is worth a choice.
create table if not exists bank_accounts (
  id             uuid primary key default gen_random_uuid(),
  bank_name      text not null,
  account_name   text not null default '',
  account_number text not null,
  sort_order     int not null default 100,
  active         boolean not null default true,
  created_at     timestamptz not null default now(),
  unique (bank_name, account_number)
);
alter table bank_accounts enable row level security;

-- What the shop is being looked at with. Anonymous: a random id kept in the
-- browser, the path, and where the visit came from. No name, no number, and
-- nothing that ties a view to a customer.
create table if not exists page_views (
  id         bigserial primary key,
  path       text not null,
  visitor    text not null,
  referrer   text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists page_views_created_idx on page_views (created_at desc);
create index if not exists page_views_visitor_idx on page_views (visitor, created_at desc);
alter table page_views enable row level security;

-- Phones that have said yes to notifications. A token is issued by Expo and
-- belongs to one install of the app, so the same person on two phones is two
-- rows, and a reinstall replaces the old one.
create table if not exists push_devices (
  token      text primary key,
  phone      text not null default '',
  platform   text not null default '',
  created_at timestamptz not null default now(),
  last_seen  timestamptz not null default now()
);
create index if not exists push_devices_phone_idx on push_devices (phone);
alter table push_devices enable row level security;

-- The account already in settings becomes the first one on the list, so
-- nothing changes for anybody the day this runs. Only into an empty table.
insert into bank_accounts (bank_name, account_name, account_number, sort_order)
select s.bank_name, s.bank_account_name, s.bank_account_number, 10
from settings s
where s.id
  and s.bank_name <> ''
  and s.bank_account_number <> ''
  and not exists (select 1 from bank_accounts);

-- How it went, in the customer's own words.
--
-- Asked once, on the order page, after the food has arrived. One rating per
-- order, so in a group each person answers for their own bag rather than the
-- person who paid answering for everybody.
alter table orders add column if not exists rating    int;
alter table orders add column if not exists feedback  text not null default '';
alter table orders add column if not exists rated_at  timestamptz;

do $rating_bounds$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'orders_rating_range'
  ) then
    alter table orders add constraint orders_rating_range
      check (rating is null or rating between 1 and 5);
  end if;
end $rating_bounds$;

-- Friends joining somebody's delivery.
--
-- Points at the order whose link they opened. It is deliberately NOT the group
-- machinery: a group renumbers its orders (#1042 becomes #1042a), and the
-- leader has already been told what to type in their transfer. Nobody's
-- reference may change because somebody else joined. Every order keeps its own
-- number, its own narration and its own payment; only the delivery is shared,
-- which is the only thing being shared in real life too.
alter table orders add column if not exists shared_with uuid references orders(id) on delete set null;
create index if not exists orders_shared_idx on orders (shared_with);

-- A shared delivery that friends are still adding to.
--
-- `closes_at` is when it stops taking people: fifteen minutes from the moment
-- it was started, and never past the run's own cut off. Until then nobody has
-- a total, because the delivery fee depends on how many end up in the car and
-- how much they order between them. `closed_at` is when it actually happened,
-- by the leader tapping close or by the clock running out.
--
-- Nobody is quoted anything before the close, which is the whole point: a
-- figure that has not been given out cannot change underneath somebody.
alter table order_groups add column if not exists closes_at timestamptz;
alter table order_groups add column if not exists closed_at timestamptz;
-- Whose job it is to pay, when the group decided one person pays for all.
alter table order_groups add column if not exists payer_phone text;
create index if not exists order_groups_closing_idx on order_groups (closes_at)
  where closed_at is null;

-- "I have finished ordering", from one person in a shared delivery.
--
-- A group closes on whichever comes first: everybody in it has said they are
-- done, the person who started it closes it by hand, or the fifteen minutes
-- runs out. Waiting on a clock when everyone is already finished would be
-- fifteen minutes of nobody being able to pay.
alter table orders add column if not exists done_at timestamptz;

-- Same day delivery, which is a different business from the batched runs.
--
-- A run carries everybody in one car and is cheap because of it. Same day is a
-- car going out for one order, at a time the customer picked, so it is priced
-- on its own ladder and kept out of the run list customers choose from.
--
-- `kind` is what keeps them apart. Every batch that already exists is a run,
-- which is why it defaults to one and why nothing changes the day this runs.
alter table batches add column if not exists kind text not null default 'run'
  check (kind in ('run', 'same_day'));
-- The time the customer asked for. Only ever set on a same day delivery.
alter table batches add column if not exists deliver_at timestamptz;
create index if not exists batches_kind_idx on batches (kind, run_date desc);

-- The two same day ladders, so the prices can be changed without a deploy,
-- exactly as the batched bands already can. Empty means the built in ones.
alter table settings add column if not exists same_day_bands text not null default '';
-- Switch same day off entirely on a day you cannot do it.
alter table settings add column if not exists same_day_on text not null default '';
-- What being inside the five hours adds, on every step of the ladder.
alter table settings add column if not exists same_day_urgent_extra text not null default '';
-- The hours of the day a delivery can be asked for, so extending the day is a
-- change of mind rather than a deploy, and so nothing in the wording has to
-- name an hour that might later be wrong.
alter table settings add column if not exists same_day_first_hour text not null default '';
alter table settings add column if not exists same_day_last_hour  text not null default '';

-- The token behind a group link.
--
-- A link has to exist the moment somebody thinks of sharing it, before they
-- have typed a name or picked a run, so it cannot hang off an order. It is a
-- random string made in the browser: the first person in the party to check
-- out creates the group under it, and everybody else who checked out with the
-- same token lands in that same group.
--
-- Unique, so two friends checking out in the same second cannot each make
-- their own group and end up in separate cars. Only ever set on a group
-- started from a link, which is why the index skips the nulls.
alter table order_groups add column if not exists party_token text;
create unique index if not exists order_groups_party_idx
  on order_groups (party_token) where party_token is not null;

-- Whether this phone wants to hear about deals. Order news is not optional:
-- it is about food somebody has already paid for.
alter table push_devices add column if not exists deals boolean not null default true;





-- Food put into a shared delivery, before there is an order for it.
--
-- In a group nobody has a delivery fee until the group closes, because it
-- depends on who else turns up. An order was still made at checkout, which
-- meant a real order, with a real number, sitting at a fee of nothing, for a
-- car nobody could buy for yet. If the group was then abandoned that number
-- was spent on nothing.
--
-- So the food waits here instead. One row per person while the group fills,
-- carrying exactly what checkout was told. When the group closes each row
-- becomes a real order, priced then, once and for all.
--
-- Nothing about price is kept here. The lines are item ids and quantities,
-- exactly as the cart posts them, and everything is priced from the menu at
-- the moment the order is made, as it always has been.
create table if not exists group_carts (
  id             uuid primary key default gen_random_uuid(),
  group_id       uuid not null references order_groups(id) on delete cascade,
  phone          text not null,
  name           text not null,
  hostel         text not null default '',
  /** What they chose: menu_item_id, qty and any option ids. */
  lines          jsonb not null,
  payment_method text not null default 'transfer',
  customer_note  text not null default '',
  coupon         text not null default '',
  /** Set when they say they have finished adding. */
  done_at        timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- One person, one place in the car. Checking out again replaces what they
  -- had rather than putting them in twice.
  unique (group_id, phone)
);
create index if not exists group_carts_group_idx on group_carts (group_id);
alter table group_carts enable row level security;


-- The shared cart, reshaped: you join by name, not by checking out.
--
-- Joining a group and ordering are two moments, and squashing them into one
-- asked for a phone number and a block before anybody had decided anything.
-- So a seat in the car is taken by name, keyed on a token this browser keeps,
-- and the number and block are filled in afterwards while everybody waits for
-- the last person to finish.
alter table group_carts add column if not exists member_token text;
alter table group_carts add column if not exists finalised_at timestamptz;
alter table group_carts alter column phone drop not null;
alter table group_carts alter column phone set default '';
alter table group_carts alter column lines set default '[]'::jsonb;

-- The seat belongs to the browser that took it, not to a number nobody has
-- given yet. Anybody already keyed by phone keeps their seat.
update group_carts set member_token = id::text where member_token is null;

do $seat_per_browser$
begin
  if exists (
    select 1 from pg_constraint where conname = 'group_carts_group_id_phone_key'
  ) then
    alter table group_carts drop constraint group_carts_group_id_phone_key;
  end if;
end $seat_per_browser$;

create unique index if not exists group_carts_seat_idx
  on group_carts (group_id, member_token);


-- A restaurant link somebody can read.
--
-- /r/a4e5104f-a815-49c8-b491-cb07325ddec7 is not a link anybody pastes into
-- a group chat. /r/dominos-pizza is. The id stays the key and old links keep
-- working; this is only a second way in.
alter table restaurants add column if not exists slug text;

-- Made from the name, once, for everything that has not got one. Anything
-- already set is left alone, because a link that has been sent out must not
-- change under it.
update restaurants
set slug = base.candidate
from (
  select
    id,
    case
      when row_number() over (partition by cleaned order by sort_order, name) = 1
        then cleaned
      else cleaned || '-' ||
           row_number() over (partition by cleaned order by sort_order, name)::text
    end as candidate
  from (
    select
      id,
      name,
      sort_order,
      -- Apostrophes go rather than becoming hyphens: Domino's Pizza is
      -- dominos-pizza, not domino-s-pizza.
      trim(both '-' from
        regexp_replace(
          regexp_replace(lower(name), '[''’`]', '', 'g'),
          '[^a-z0-9]+', '-', 'g'
        )
      ) as cleaned
    from restaurants
  ) tidy
  where cleaned <> ''
) base
where restaurants.id = base.id
  and (restaurants.slug is null or restaurants.slug = '');

create unique index if not exists restaurants_slug_idx
  on restaurants (slug) where slug is not null and slug <> '';


-- What the food actually cost at the counter.
--
-- Profit was worked out as what customers paid for food minus what customers
-- paid for food, which assumes every plate cost exactly the menu price. It
-- often does not: turn up in person often enough and a counter gives it to
-- you for less, and that discount is the shop's margin, sitting invisible.
--
-- Zero means nothing was typed in and the menu prices stand, so nothing
-- changes for any run where this is left alone.
alter table batches add column if not exists food_spend int not null default 0;


-- What each thing actually cost at the counter.
--
-- The menu price is what the customer paid, not what the shop paid. Turn up
-- in person and a counter often charges less, sometimes more, and profit was
-- being worked out as though it were always exactly the same. This is where
-- the real figure goes, one row per thing bought on one run.
--
-- Kept per line rather than as a single total so it can be corrected later
-- without retyping the lot, and so the run sheet can show what moved.
create table if not exists counter_spend (
  id         uuid primary key default gen_random_uuid(),
  batch_id   uuid not null references batches(id) on delete cascade,
  /** Restaurant, item and choices, as the counter list groups them. */
  line_key   text not null,
  /** What was handed over for that line in total, not per unit. */
  paid       int not null default 0 check (paid >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, line_key)
);
create index if not exists counter_spend_batch_idx on counter_spend (batch_id);
alter table counter_spend enable row level security;

-- What the customer handed back when the counter charged well over the menu.
--
-- Asking somebody for the difference on a plate that went up two hundred
-- naira is not worth the conversation, but on a big gap it is, and when they
-- pay it the shop is not out of pocket. Without somewhere to put it, that
-- money never reached the books and the run read as a loss it had not made.
alter table counter_spend add column if not exists recovered int not null default 0
  check (recovered >= 0);

-- Which restaurants a code works on. A code like AWOF is a deal with one
-- kitchen, not a discount on anything the shop carries, so it has to hold to
-- that kitchen and no other.
--
-- With no rows here it works on anything, which is what every code written
-- before today is. With rows, the whole cart has to come from those places:
-- a code for Domino's on a cart of Domino's and a shawarma is a code being
-- spent on the shawarma too, and the deal does not cover that.
create table if not exists coupon_restaurants (
  coupon_code   text not null references coupons(code) on delete cascade,
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  primary key (coupon_code, restaurant_id)
);
create index if not exists coupon_restaurants_place_idx
  on coupon_restaurants (restaurant_id);
alter table coupon_restaurants enable row level security;


-- Getting there and back, apart from the fuel.
--
-- A run is a keke to the junction, a bike with the bags, sometimes a car when
-- there is too much to carry. That is not fuel and it is not the driver, and
-- putting it under Anything else meant the one cost that changes most from
-- run to run was buried in a box with the bags and the gate fee.
alter table batches add column if not exists transport_cost int not null default 0;


-- A promotion: a code that needs no typing, and sets the delivery rather than
-- taking money off it.
--
-- "Order Domino's, delivery is 2,000" is not a discount on the ladder, it is
-- a different price entirely: five items or one, it is 2,000. And nobody
-- types anything, because a price nobody has to know a word for is a price
-- everybody gets.
--
-- It lives with the codes rather than beside them because it is the same
-- thing in every other respect: one restaurant, chosen runs, an expiry, a cap
-- on how many orders it is good for, an on and off switch, and the strip
-- along the top that reads the offer rather than repeating a sentence.
alter table coupons add column if not exists automatic boolean not null default false;

-- How many items the headline price covers, and what each one after that
-- costs. "2,000 for three, 500 an item after" is still one price somebody can
-- say out loud, and it stops one person filling the boot for the price of a
-- pizza without a cliff where the offer suddenly stops applying.
--
-- Blank included_items means truly flat, however much they order.
alter table coupons add column if not exists included_items int;
alter table coupons add column if not exists extra_per_item int not null default 0
  check (extra_per_item >= 0);

-- Which same day windows it is good for, as the hour each one starts, comma
-- separated: "12,15". Empty means every window, and a run is not a window so
-- runs are unaffected by this.
--
-- The hour rather than a time: the windows on offer slide through the day as
-- it gets late, so anything fixed to an instant would stop matching by two
-- o'clock. An order belongs to a window if its delivery hour falls inside it.
alter table coupons add column if not exists windows text not null default '';

-- A promotion in a group: split, but never below this each.
--
-- Two thousand each was more than most of them pay today, so the group would
-- simply not use it. Split with a floor keeps the reason to bring somebody:
-- on your own it is the whole two thousand, with a friend it is a thousand
-- each, and it stops falling there rather than running to nothing at twenty.
--
-- Zero is a plain split, and setting it to the fee itself is a flat price
-- per head.
alter table coupons add column if not exists min_per_person int not null default 0
  check (min_per_person >= 0);

-- "fee" is the promotion: the delivery becomes this amount, rather than this
-- amount coming off it.
do $$
begin
  alter table coupons drop constraint if exists coupons_applies_to_check;
  alter table coupons add constraint coupons_applies_to_check
    check (applies_to in ('delivery', 'order', 'fee'));
end $$;

-- An automatic offer has no code to type, but the table is keyed by code and
-- the strip names one, so it still has one. This keeps two automatic offers
-- from both claiming the same order, which is the one thing that must not
-- happen: a checkout carries one offer.
create index if not exists coupons_automatic_idx on coupons (automatic) where automatic;


-- Which dishes an offer is for, where it is for particular dishes rather than
-- a whole kitchen.
--
-- "Order the BBQ beef medium and delivery is free" is the same kind of thing
-- as "Domino's delivery is 2,000": it applies by itself, it is good on
-- chosen runs and chosen windows, it has a cap and an expiry. The only
-- difference is what makes a cart qualify. So it is an offer with an item
-- list rather than a flag on the dish, which would have had nowhere to keep
-- any of that.
--
-- Two of them together still qualify: each was worth the trip on its own.
create table if not exists coupon_items (
  coupon_code  text not null references coupons(code) on delete cascade,
  menu_item_id uuid not null references menu_items(id) on delete cascade,
  primary key (coupon_code, menu_item_id)
);
create index if not exists coupon_items_item_idx on coupon_items (menu_item_id);
alter table coupon_items enable row level security;

-- Free delivery is a fee of nothing, so the fee can be nothing.
do $$
begin
  alter table coupons drop constraint if exists coupons_amount_check;
  alter table coupons add constraint coupons_amount_check check (amount >= 0);
end $$;


-- Which parts of a menu an offer is for, where it is a whole section rather
-- than a handful of dishes.
--
-- "Any pizza" is one tick here instead of forty in the dish list, and it
-- keeps up: a pizza added to the menu next week is in the offer without
-- anybody remembering to add it. The categories are resolved to their dishes
-- each time the offer is read, so nothing goes stale.
create table if not exists coupon_categories (
  coupon_code text not null references coupons(code) on delete cascade,
  category_id uuid not null references menu_categories(id) on delete cascade,
  primary key (coupon_code, category_id)
);
create index if not exists coupon_categories_category_idx
  on coupon_categories (category_id);
alter table coupon_categories enable row level security;

-- A choice every line has to have made, by the name of the option: "Large".
--
-- Size is a choice on a dish rather than a dish of its own, so "any large
-- pizza" cannot be said with a list of dishes at all. It is the pizza section
-- plus this.
--
-- Matched on the name because each dish carries its own copy of the option,
-- so there is no one Large to point at. That puts weight on naming them the
-- same way, which is why admin says how many of the dishes it is actually
-- catching rather than leaving it to be found out on a Friday.
alter table coupons add column if not exists required_choice text not null default '';


-- Delivery hours per weekday.
--
-- Saturday and Wednesday are not the same business: the shop can be out at
-- noon on a Saturday and not before three on a weekday, and one pair of hours
-- for the whole week meant picking whichever was wrong more often.
--
-- JSON, keyed by weekday as JavaScript counts them, 0 for Sunday:
--   {"0":{"first":12,"last":18},"1":{"off":true}}
-- A day that is not named falls back to the single pair above it, so a shop
-- that never touches this works exactly as it did.
alter table settings add column if not exists same_day_day_hours text not null default '';


-- When the books on a run were closed.
--
-- Delivered is about the food; this is about the money. A run that has been
-- driven still has a counter sheet to reconcile, fuel to put in and the odd
-- unpaid order to chase, and until somebody says otherwise there is no way to
-- tell a run that is finished from one that merely arrived.
--
-- Set, the run reads as history: a summary of what it came to, rather than a
-- page of controls for work that is done.
alter table batches add column if not exists settled_at timestamptz;


-- The wording for asking somebody how the food was.
--
-- A delivered order has nothing left to say about payment or lateness, so
-- the one message worth offering on it is this one.
alter table settings add column if not exists msg_review text not null default '';


-- Short links for an order and for a group.
--
-- A link gets pasted into a chat, and a thirty-six character identifier in
-- the middle of one looks like something has gone wrong. This is seven
-- characters instead, from an alphabet with no o, l, i, 0 or 1 in it, so a
-- link read off a screen and typed by hand cannot land on somebody else's
-- order.
--
-- It is not a secret in the cryptographic sense, but nor was the identifier
-- it replaces: both are unguessable enough that nobody is going to find a
-- stranger's order by trying, and there are thirty billion of them.
create or replace function short_code() returns text
language sql volatile as $$
  select string_agg(
    substr('23456789abcdefghjkmnpqrstuvwxyz', (floor(random() * 31)::int) + 1, 1),
    ''
  )
  from generate_series(1, 7);
$$;

-- Added empty, filled row by row, and only then made unique: a default on a
-- table this size is one statement that either works or locks, and this way
-- each step is small enough to see.
alter table orders        add column if not exists short text;
alter table order_groups  add column if not exists short text;

update orders       set short = short_code() where short is null;
update order_groups set short = short_code() where short is null;

create unique index if not exists orders_short_idx       on orders (short);
create unique index if not exists order_groups_short_idx on order_groups (short);

alter table orders       alter column short set default short_code();
alter table order_groups alter column short set default short_code();


-- Whether an offer reaches a car somebody has to themselves.
--
-- A promotion is built for a shared run: a flat two thousand makes sense
-- across a car with ten bags in it. The same two thousand on a same day trip,
-- which goes out for one person and is priced at six and a half, is not a
-- discount, it is driving at a loss once per order.
--
-- So it is off unless somebody says otherwise, and every offer written before
-- today becomes runs only, which is what they were all meant to be.
alter table coupons add column if not exists same_day boolean not null default false;

-- Supabase caches the schema; this makes the new columns visible immediately.
notify pgrst, 'reload schema';


-- How somebody pays, kept with their name and their block.
--
-- It lived in one browser, so a regular who always pays by card was put back
-- on a bank transfer by a new phone, a cleared browser, or simply opening the
-- app instead of the site. It is a fact about the person, like where they
-- live, and it belongs where those are.
--
-- Written on every order, so it follows whatever they actually did last, and
-- read back when checkout fills itself in.
alter table customers add column if not exists payment_method text not null default 'transfer';

-- Supabase caches the schema; this makes the new column visible immediately.
notify pgrst, 'reload schema';


-- Which seat in a shared delivery an order came out of.
--
-- Closing a group turns the seats into orders and deletes the seats, and with
-- them the only thing tying a person's browser to their own order. So the
-- board could not tell one member's line from another's, and only whoever
-- pressed close was taken to their total: everybody else landed on the split
-- and had to find themselves in a list.
--
-- Written as each order is made. Nothing reads it but the group board, and a
-- close works whether or not this has been run.
alter table orders add column if not exists seat_token text;

-- Supabase caches the schema; this makes the new column visible immediately.
notify pgrst, 'reload schema';


-- A checkout link: a basket somebody made by hand, ready to send.
--
-- "I am going to Domino's, the meatball pizza is on offer, here is a link."
-- Whoever taps it says who they are and where it goes, and that is the whole
-- order. The food is fixed by whoever made the link; the price is not, because
-- prices and promotions live on the menu and this must never disagree with it.
create table if not exists checkout_links (
  id           uuid primary key default gen_random_uuid(),
  short        text unique not null default short_code(),
  -- What it is for, so a list of links is readable a week later.
  label        text not null default '',
  -- The basket, as ordinary cart lines: item, quantity, chosen options.
  lines        jsonb not null default '[]'::jsonb,
  -- The run it goes on. Null means whichever run is taking orders when they
  -- tap it, which is what a link sent to a group chat wants.
  batch_id     uuid references batches(id) on delete set null,
  -- Or a time they are going anyway, which makes its own car when the first
  -- person orders, exactly as a same day order does.
  deliver_at   timestamptz,
  -- What delivery costs on this one, when it is not what the ladder would
  -- say: a shop run that is going regardless, a favour, a flat price agreed
  -- with a hostel. Null leaves the ordinary rules, promotions and all.
  fee          int,
  -- A code applied for them, so nobody has to be told to type it.
  coupon_code  text,
  -- A card link, when there is one, so paying by card needs no message.
  payment_link text not null default '',
  note         text not null default '',
  active       boolean not null default true,
  used         int not null default 0,
  created_at   timestamptz not null default now()
);

create index if not exists checkout_links_short_idx on checkout_links (short);

alter table checkout_links enable row level security;

-- Supabase caches the schema; this makes the new table visible immediately.
notify pgrst, 'reload schema';


-- When a run actually arrives, as times rather than as a sentence.
--
-- The window was typed out by hand, so the shop knew what it had promised
-- only as words: "Between 12pm and 5.30pm" could not be compared with
-- anything. Times can be, which is what lets a same day window that a run
-- already covers be left out of the list instead of being guessed at.
--
-- The sentence the customer reads is built from these. The old free text
-- stays as the fallback, so nothing changes until these are filled in.
alter table settings add column if not exists window_afternoon_from text not null default '';
alter table settings add column if not exists window_afternoon_to   text not null default '';
alter table settings add column if not exists window_night_from     text not null default '';
alter table settings add column if not exists window_night_to       text not null default '';

-- Supabase caches the schema; this makes the new columns visible immediately.
notify pgrst, 'reload schema';


-- Other things somebody can have off the same link.
--
-- "I am going to Domino's, here is the meatball" is a link one person says
-- yes to and another closes, because what they wanted was the chicken. These
-- are the dishes they can have instead: picked here, priced from the menu
-- like everything else, and swapped in place of what the link came with.
--
-- Cart lines, the same shape as the basket itself, so a size or a flavour is
-- settled here too.
alter table checkout_links add column if not exists alternatives jsonb not null default '[]'::jsonb;

-- Supabase caches the schema; this makes the new column visible immediately.
notify pgrst, 'reload schema';

-- Skincare: the same shop, a different delivery day.
--
-- Everything about a product is already what a menu item is: a name, a price,
-- a picture, a section of a menu it sits under. So skincare is a restaurant
-- row like any other, marked as such, and every part of the machine that
-- knows how to price a line, take a payment and show somebody their order
-- goes on working without being told about it.
--
-- What is different is when it arrives. There is one car a week, on a
-- Saturday, and a cut off on the Saturday morning. Order after it and the
-- next one is a week later: you can still order, it is only the arriving that
-- waits.
alter table restaurants add column if not exists kind text not null default 'food';

do $$
begin
  alter table restaurants drop constraint if exists restaurants_kind_check;
  alter table restaurants add constraint restaurants_kind_check
    check (kind in ('food', 'skincare'));
end $$;

-- A skincare drop is a batch, because the stages, the run sheet and the order
-- page all already understand batches. `kind` is what keeps it out of the run
-- list customers pick a car from.
do $$
begin
  alter table batches drop constraint if exists batches_kind_check;
  alter table batches add constraint batches_kind_check
    check (kind in ('run', 'same_day', 'skincare'));
end $$;

-- One run per slot per day, which is what that rule was always for. It was
-- written when every batch was a run, so a car going out for one person, or a
-- Saturday skincare drop, collided with the run already on that day and was
-- refused: the insert failed and the customer was told the batch no longer
-- existed, which was not what had happened.
alter table batches drop constraint if exists batches_run_date_slot_key;
create unique index if not exists batches_one_run_per_slot
  on batches (run_date, slot) where kind = 'run';

alter table settings add column if not exists skincare_on text not null default '';
-- One flat fee for a skincare order, whatever is in it. A Saturday drop with
-- everybody's parcels in one car is not priced like a Domino's run, and it is
-- not worth a ladder of its own.
alter table settings add column if not exists skincare_fee int not null default 0;
-- Which day the car goes, as a weekday: 0 Sunday through 6 Saturday.
alter table settings add column if not exists skincare_day int not null default 6;
-- The cut off on that morning, and the window the car delivers in. Both in
-- the shop's own words, both editable without a deploy.
alter table settings add column if not exists skincare_cut_off text not null default '08:00';
alter table settings add column if not exists skincare_window text not null default '';
alter table settings add column if not exists skincare_blurb text not null default '';

-- Whose product it is, and the picture it came with.
--
-- Skincare is broad in a way a restaurant menu is not: CeraVe and Bioderma
-- are not two sections of one shelf, they are the first thing somebody
-- narrows by. The brand is a column rather than a category because a product
-- has both, a section and a maker, and folding one into the other loses a
-- filter people actually use.
alter table menu_items add column if not exists brand text not null default '';
-- The file its picture is expected to arrive as, slugified from the title.
-- Matching a photograph to a product by the look of its name is guesswork on
-- two thousand of them; matching it to the filename the export named is not.
alter table menu_items add column if not exists image_file text not null default '';
create index if not exists menu_items_image_file_idx on menu_items (image_file)
  where image_file <> '';

-- Every shelf a product sits on, not just one.
--
-- A shop's own sections overlap on purpose: a cleanser is under Cleansers and
-- under Korean Skin Care, and a shelf that has to pick one loses whichever it
-- did not pick. Kept as "|Cleansers|Korean Skin Care|" so a filter is a
-- substring match on the name with its bars, which cannot half-match
-- "Skin Care" against "Korean Skin Care".
alter table menu_items add column if not exists shelves text not null default '';

-- Delivery on a skincare order, as a ladder rather than one number.
--
-- It is the car, not the cream: four bottles and fifteen bottles do not take
-- the same room, and the flat fee it started as charged them the same. Empty
-- falls back to the flat fee above, so nothing changes until a ladder is
-- written.
alter table settings add column if not exists skincare_bands text not null default '';

-- Why the products are real.
--
-- Nothing on the shelf said where any of it comes from, and skincare is the
-- one thing people are right to be careful about: a counterfeit serum is not
-- a disappointing dinner, it is somebody's face. Kept as a setting because it
-- is a claim about how the shop buys, and that is the shop's to word.
alter table settings add column if not exists skincare_promise text not null default '';

-- Restaurants that are not in Sangotedo.
--
-- The whole shop was built around one parade of shops twenty minutes from
-- campus, so one delivery ladder was the truth. A restaurant further out is a
-- longer trip and a dearer one, and charging the Sangotedo price for it is
-- losing money on every order without noticing.
--
-- An area, rather than a price on each restaurant: the cost is the distance,
-- not the kitchen, and four restaurants in the same place should not be four
-- numbers to keep in step.
alter table restaurants add column if not exists area text not null default '';

-- The areas themselves, as JSON, so adding one is a change of mind rather
-- than a deploy. Each carries what it adds to the two ladders, because the
-- ladders themselves are about how much room an order takes and that does not
-- change with the distance: a run to Lekki is the Sangotedo ladder plus the
-- extra petrol, at every band.
--
-- Empty is the state everything is in today: one area, no extra, and every
-- price exactly as it was.
alter table settings add column if not exists delivery_areas text not null default '';

-- Which areas a run actually goes to.
--
-- A run is a car with a route. It always passes Sangotedo, and it goes
-- anywhere else only because somebody said so when it was made: a Thursday
-- run that was never going to Lekki cannot pick up a Lekki order because
-- somebody put one in the basket. Kept as "|lekki|ikeja|" so the check is an
-- exact match on a name with its bars.
alter table batches add column if not exists areas text not null default '';

-- Delivery priced by what the shopping comes to, for the places where the
-- container count is the wrong question.
--
-- A restaurant's ladder counts containers, because a car carrying twelve
-- takeaway boxes is a different car from one carrying two. A market is not
-- like that: eleven peppers and a bag of rice is one trip and two bags, and
-- counting them as eleven containers charges somebody nine thousand naira to
-- be brought their vegetables. Bulk is what costs more there, and the honest
-- measure of bulk is the money.
--
-- Empty, which is every restaurant today, means the ordinary ladder.
alter table restaurants add column if not exists value_bands text not null default '';

-- Which admin emails to stop sending.
--
-- Every notification went to everybody on the list, with no way to turn one
-- off short of taking your address out altogether and losing the lot. An
-- afternoon of testing is then an inbox of "New order #1004 · fgxdfg", and a
-- real order arriving in the middle of that is one nobody sees.
--
-- The ones to stop, rather than the ones to send, so empty means everything
-- exactly as it is today and nobody's notifications go quiet because a
-- migration ran.
alter table settings add column if not exists email_mute text not null default '';

-- Letting a promoter's code change without losing who they brought.
--
-- The code is the key: a customer carries it for life, an order carries it,
-- a payout is filed under it. So renaming one meant orphaning all of that,
-- and being stuck with whatever was typed the day somebody was set up is a
-- poor reason to say no to them.
--
-- The database can move the children itself. Every reference becomes ON
-- UPDATE CASCADE, so a rename is one update and nothing is left pointing at
-- a code that no longer exists.
do $$
begin
  alter table customers drop constraint if exists customers_promoter_code_fkey;
  alter table customers add constraint customers_promoter_code_fkey
    foreign key (promoter_code) references promoters(code)
    on delete set null on update cascade;
exception when others then
  -- A database where that constraint was never named this way keeps what it
  -- has. A rename then refuses outright rather than half happening.
  raise notice 'customers.promoter_code left as it was';
end $$;

do $$
begin
  alter table orders drop constraint if exists orders_promoter_code_fkey;
  alter table orders add constraint orders_promoter_code_fkey
    foreign key (promoter_code) references promoters(code)
    on delete set null on update cascade;
exception when others then
  raise notice 'orders.promoter_code left as it was';
end $$;

do $$
begin
  alter table promoter_payouts drop constraint if exists promoter_payouts_promoter_code_fkey;
  alter table promoter_payouts add constraint promoter_payouts_promoter_code_fkey
    foreign key (promoter_code) references promoters(code)
    on delete cascade on update cascade;
exception when others then
  raise notice 'promoter_payouts.promoter_code left as it was';
end $$;
