-- Sudu Delivery: everything added since the first setup.
--
-- Safe to run more than once, and safe to run on a database that already has
-- some of it. Run this instead of setup.sql when the Supabase SQL editor
-- deadlocks on the storage policy: nothing here touches storage.

-- Everyone named in a group order, with the number to call when the food
-- lands. Without this a one-payer group knew the names on the bags but had no
-- way to reach the people they belong to.
create table if not exists group_members (
  id         uuid primary key default gen_random_uuid(),
  group_id   uuid not null references order_groups(id) on delete cascade,
  name       text not null,
  phone      text not null default '',
  hostel     text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists group_members_group_idx on group_members (group_id);
alter table group_members enable row level security;

-- The card link generated by hand, kept so it can be sent again.
alter table orders add column if not exists payment_link text;

-- A short number a person can say out loud.
create sequence if not exists order_no_seq start 1001;
alter table orders add column if not exists order_no bigint;
alter table orders alter column order_no set default nextval('order_no_seq');
update orders set order_no = nextval('order_no_seq') where order_no is null;
create unique index if not exists orders_order_no_idx on orders (order_no);

-- Editable message templates, and the line a paid customer reads.
alter table settings add column if not exists msg_confirmed text not null default '';
alter table settings add column if not exists msg_payment   text not null default '';
alter table settings add column if not exists msg_card      text not null default '';
alter table settings add column if not exists msg_pin       text not null default '';
alter table settings add column if not exists msg_ready     text not null default '';
alter table settings add column if not exists msg_late      text not null default '';
alter table settings add column if not exists paid_note     text not null default '';

-- What a run actually costs to make: fuel, whoever drove, and anything else
-- bought on the night. Without these the sheet could only say what was left
-- before those, which is not profit.
alter table batches add column if not exists fuel_cost   int not null default 0;
alter table batches add column if not exists driver_cost int not null default 0;
alter table batches add column if not exists other_cost  int not null default 0;
alter table batches add column if not exists cost_note   text not null default '';

-- The delivery price list, so it can be changed without a deploy.
alter table settings add column if not exists fee_bands text not null default '';

-- Supabase caches the schema; this makes the new columns visible immediately.
notify pgrst, 'reload schema';
