"use server";

import { normalisePhone } from "@/lib/phone";
import { redirect } from "next/navigation";
import { revalidatePath, updateTag } from "next/cache";
import { isSignedIn, passwordMatches, signIn, signOut } from "@/lib/admin-auth";
import { batchSheet, stillOpen } from "@/lib/admin";
import { db } from "@/lib/supabase";
import { STAGES, type BatchStage } from "@/lib/stages";
import { type BatchSlot } from "@/lib/config";
import { hoursByDay, deliveryWindows, externalUrl } from "@/lib/settings";
import { runSchedule } from "@/lib/schedule";
import { deliverySlots } from "@/lib/same-day";
import { lagosInstant, lagosToday } from "@/lib/time";
import { clearDeadGroups, ensureUpcomingBatches, openRunsBetween } from "@/lib/batches";
import { closeGroup } from "@/lib/groups";
import { canTravel, groupCarts } from "@/lib/group-carts";
import {
  deleteCheckoutLink,
  saveCheckoutLink,
  setCheckoutLinkActive,
} from "@/lib/checkout-links";
import { fileFrom, uploadImage } from "@/lib/uploads";
import { parseMenuText } from "@/lib/menu-import";
import { newPin } from "@/lib/customer-auth";
import { pushDeal, pushToPhone } from "@/lib/push";

async function assertAdmin(): Promise<void> {
  if (!(await isSignedIn())) throw new Error("Not signed in.");
}

export async function login(
  _prev: { error: string | null },
  form: FormData
): Promise<{ error: string | null }> {
  if (!passwordMatches(String(form.get("password") ?? ""))) {
    return { error: "Wrong password." };
  }
  await signIn();
  revalidatePath("/admin", "layout");
  return { error: null };
}

export async function logout(): Promise<void> {
  await signOut();
  revalidatePath("/admin", "layout");
}

/**
 * Manual "mark paid". The transfer is matched by the phone number in the
 * narration. This is replaced by a Paystack webhook once reconciliation stops
 * being trivial (brief §13), which is why payment_ref exists from day one.
 */
export async function markPaid(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("order_id"));
  const ref = String(form.get("payment_ref") ?? "").trim();

  await db()
    .from("orders")
    .update({
      status: "paid",
      paid_at: new Date().toISOString(),
      payment_ref: ref || null,
    })
    .eq("id", id);

  // If they have the app, tell them. Not awaited by anything that matters,
  // and a failure here leaves the order paid all the same.
  void (async () => {
    try {
      const { data } = await db()
        .from("orders")
        .select("customer_phone, customer_name")
        .eq("id", id)
        .maybeSingle();
      const row = data as { customer_phone: string; customer_name: string } | null;
      if (!row) return;

      await pushToPhone(row.customer_phone, {
        title: "Payment confirmed",
        body: `Thanks ${row.customer_name.split(" ")[0]}. Your food is on this run.`,
        path: `/o/${id}`,
      });
    } catch {
      /* Nothing said is better than an order that would not save. */
    }
  })();

  revalidatePath("/admin", "layout");
}

/**
 * The card link is generated by hand in a payment app and pasted here, so it
 * can be sent again without generating another one.
 */
export async function savePaymentLink(form: FormData): Promise<void> {
  await assertAdmin();
  // Stored with its scheme, so it is a link to somewhere else rather than a
  // path on this site.
  const link = externalUrl(String(form.get("payment_link") ?? ""));

  await db()
    .from("orders")
    .update({ payment_link: link })
    .eq("id", String(form.get("order_id")));

  revalidatePath("/admin", "layout");
  }

/**
 * Ticking a bag off marks everything in it delivered, and untricking it puts
 * it back to paid. The tick used to be a private checklist in the browser
 * that looked identical to the real thing, so a bag could be ticked all
 * evening while its customer's page still read "paid and on the run".
 */
export async function setBagDelivered(form: FormData): Promise<void> {
  await assertAdmin();
  const ids = String(form.get("order_ids") ?? "")
    .split(",")
    .map((id) => id.trim())
    .filter(Boolean);
  if (ids.length === 0) return;

  const delivered = form.get("delivered") === "true";
  await db()
    .from("orders")
    .update({ status: delivered ? "delivered" : "paid" })
    .in("id", ids);

  revalidatePath("/admin", "layout");
  revalidatePath("/orders");
  revalidatePath("/o", "layout");
}

export async function markDelivered(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("orders")
    .update({ status: "delivered" })
    .eq("id", String(form.get("order_id")));
  revalidatePath("/admin", "layout");
}

/** Refunds are same-night and in full. There are no partial refunds here. */
export async function refundOrder(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("orders")
    .update({ status: "refunded" })
    .eq("id", String(form.get("order_id")));
  revalidatePath("/admin", "layout");
}

export async function setBatchStatus(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("batches")
    .update({ status: String(form.get("status")) })
    .eq("id", String(form.get("batch_id")));
  revalidatePath("/admin", "layout");
}

/**
 * What the run cost to make. Typed in on the night, so the money tab can show
 * profit rather than "left before fuel and driver".
 */
/**
 * What things actually cost at the counter, line by line.
 *
 * Only the lines somebody typed something into. Most of the time one or two
 * prices moved and the rest were exactly the menu, so a blank means "the menu
 * was right" rather than "this was free", and clearing a figure puts that
 * line back to the menu price.
 */
export async function setCounterSpend(form: FormData): Promise<void> {
  await assertAdmin();
  const batchId = String(form.get("batch_id") ?? "");
  if (!batchId) return;

  const keys = form.getAll("line_key").map(String);
  const typed = form.getAll("paid").map(String);

  for (const [index, key] of keys.entries()) {
    const raw = (typed[index] ?? "").trim();
    const value = Math.round(Number(raw));

    if (raw === "" || !Number.isFinite(value) || value < 0) {
      // Back to the menu price for that one thing.
      await db()
        .from("counter_spend")
        .delete()
        .eq("batch_id", batchId)
        .eq("line_key", key);
      continue;
    }

    // What the customer handed back, when they were asked to cover a gap.
    // Blank is none, which is the usual answer.
    const backRaw = String(form.getAll("recovered")[index] ?? "").trim();
    const back = Math.round(Number(backRaw));
    const recovered = backRaw !== "" && Number.isFinite(back) && back > 0 ? back : 0;

    await db()
      .from("counter_spend")
      .upsert(
        {
          batch_id: batchId,
          line_key: key,
          paid: value,
          recovered,
          updated_at: new Date().toISOString(),
        },
        { onConflict: "batch_id,line_key" }
      );
  }

  revalidatePath("/admin", "layout");
}

/**
 * Put a menu price up, because a counter really has put it up.
 *
 * Only ever upward, and only from a figure somebody typed after paying it.
 * A counter charging less is usually a promo or a good mood on the day, and
 * following it down would drop the shop's own price on the strength of one
 * afternoon. Charging more tends to stay charged, and a menu that is behind
 * loses money on every order until somebody notices.
 *
 * Never automatic. The figure came from a phone at a counter, so a slipped
 * digit would otherwise raise a price nobody meant to raise.
 */
export async function raiseMenuPrice(form: FormData): Promise<void> {
  await assertAdmin();

  const itemId = String(form.get("item_id") ?? "");
  const by = Math.round(Number(form.get("by") ?? 0));
  if (!itemId || !Number.isFinite(by) || by <= 0) return;

  const { data: item } = await db()
    .from("menu_items")
    .select("price_food")
    .eq("id", itemId)
    .maybeSingle();
  if (!item) return;

  await db()
    .from("menu_items")
    .update({ price_food: (item.price_food as number) + by })
    .eq("id", itemId);

  updateTag("menu");
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * Move a same day car into another window.
 *
 * Somebody asks for three to six, you ring them, and they are happy to have
 * it at lunchtime instead. That turns two shopping trips into one, and the
 * only way to say so was to have no way to say so.
 *
 * Moving it is all that is needed: trips are clustered by the time asked for,
 * so a car moved into another window joins that trip on its own.
 *
 * The customer is not told by this. It comes from a phone call, so the
 * agreement already happened; changing it here is writing down what was said.
 */
export async function moveSameDayCar(form: FormData): Promise<void> {
  await assertAdmin();

  const id = String(form.get("batch_id") ?? "");
  const at = String(form.get("deliver_at") ?? "");
  if (!id || !at) return;

  const { data: batch } = await db()
    .from("batches")
    .select("kind, stage")
    .eq("id", id)
    .maybeSingle();

  // Only a car, and only one that has not been bought for yet: moving a
  // delivery after the food is in the boot moves nothing but the record.
  if (!batch || batch.kind !== "same_day") return;
  if (batch.stage !== "ordering") return;

  const slot = (await deliverySlots(new Date(), await hoursByDay())).find(
    (one) => one.at === at
  );
  if (!slot) return;

  await db()
    .from("batches")
    .update({
      deliver_at: slot.at,
      delivery_window_text: slot.label,
      run_date: lagosToday(new Date(slot.at)),
      // The enum only knows the two, and nothing reads it on a same day car.
      slot: new Date(slot.at).getUTCHours() >= 16 ? "night" : "afternoon",
    })
    .eq("id", id);

  revalidatePath("/admin", "layout");
  revalidatePath("/");
}

export async function setRunCosts(form: FormData): Promise<void> {
  await assertAdmin();
  const money = (field: string) => {
    const value = Math.round(Number(form.get(field) ?? 0));
    return Number.isFinite(value) && value > 0 ? value : 0;
  };

  // The food is priced at the counter now, item by item, so this form no
  // longer carries a figure for the whole shop. Runs reconciled the old way
  // keep theirs: absent means leave it alone, not set it to nothing.
  const whole = form.has("food_spend") ? { food_spend: money("food_spend") } : {};

  const id = String(form.get("batch_id"));
  const costs = {
    fuel_cost: money("fuel_cost"),
    driver_cost: money("driver_cost"),
    other_cost: money("other_cost"),
    ...whole,
    cost_note: String(form.get("cost_note") ?? "").trim(),
  };

  // Transport is the newest of these. Naming a column the database has not
  // been given yet fails the whole update, which would lose the fuel and the
  // driver along with it, so it is tried and then dropped.
  const { error } = await db()
    .from("batches")
    .update({ ...costs, transport_cost: money("transport_cost") })
    .eq("id", id);
  if (error) await db().from("batches").update(costs).eq("id", id);

  revalidatePath("/admin", "layout");
}

/**
 * When a run lands and when it closes, changed after the run exists. A run
 * that slips by an hour has to be able to say so without being recreated.
 */
export async function updateRun(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("batch_id"));

  const { data: batch } = await db()
    .from("batches")
    .select("run_date, slot")
    .eq("id", id)
    .maybeSingle();
  if (!batch) return;

  const orders = await orderCount(id);
  // The day and the slot decide which orders belong where, so they only move
  // while the run is still empty. The window and the cut-off change any time.
  const runDate =
    orders === 0 && String(form.get("run_date") ?? "").trim()
      ? String(form.get("run_date")).trim()
      : (batch.run_date as string);
  const slot =
    orders === 0 && String(form.get("slot") ?? "")
      ? String(form.get("slot"))
      : (batch.slot as string);

  const patch: Record<string, string> = {
    run_date: runDate,
    slot,
    delivery_window_text: String(form.get("delivery_window_text") ?? "").trim(),
  };

  const time = String(form.get("cut_off_time") ?? "").trim();
  if (/^\d{2}:\d{2}$/.test(time)) {
    const [hour, minute] = time.split(":").map(Number);
    patch.cut_off_at = lagosInstant(runDate, hour, minute);
  }

  await db().from("batches").update(patch).eq("id", id);

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** One line of the weekly schedule: a day, a slot, a cut-off and a window. */
export async function saveScheduleRun(form: FormData): Promise<void> {
  await assertAdmin();
  const weekday = Number(form.get("weekday"));
  const slot = String(form.get("slot") ?? "afternoon");
  const cutOff = String(form.get("cut_off") ?? "").trim();
  if (!Number.isInteger(weekday) || weekday < 0 || weekday > 6) return;
  if (!/^\d{2}:\d{2}$/.test(cutOff)) return;

  const { error } = await db()
    .from("run_schedule")
    .upsert(
      {
        weekday,
        slot,
        cut_off: cutOff,
        window_text: String(form.get("window_text") ?? "").trim(),
        // Saving a time must not quietly bring a paused day back.
        active: form.get("active") !== "false",
      },
      { onConflict: "weekday,slot" }
    );
  if (error) throw new Error(`Could not save that day: ${error.message}`);

  // The runs already opened for that day follow the new time. Only ones still
  // to come, and only while nothing has been ordered on them: a run with
  // orders keeps the cut-off and the delivery time its customers were told.
  const windowText = String(form.get("window_text") ?? "").trim();
  const { data: rows } = await db()
    .from("batches")
    .select("id, run_date")
    .eq("slot", slot)
    .gte("run_date", lagosToday());

  // Midday UTC, so the day cannot slip either side of midnight.
  const sameDay = ((rows ?? []) as { id: string; run_date: string }[]).filter(
    (row) => new Date(`${row.run_date}T12:00:00Z`).getUTCDay() === weekday
  );

  if (sameDay.length > 0) {
    const ids = sameDay.map((row) => row.id);
    const { data: taken } = await db().from("orders").select("batch_id").in("batch_id", ids);
    const busy = new Set((taken ?? []).map((row) => row.batch_id as string));
    const [hour, minute] = cutOff.split(":").map(Number);

    for (const row of sameDay) {
      if (busy.has(row.id)) continue;
      await db()
        .from("batches")
        .update({
          cut_off_at: lagosInstant(row.run_date, hour, minute),
          ...(windowText ? { delivery_window_text: windowText } : {}),
        })
        .eq("id", row.id);
    }
  }

  revalidatePath("/admin", "layout");
}

/**
 * Removes a day from the schedule. Runs already opened for it are left alone:
 * they are deleted one at a time, and only while nothing has been ordered.
 */
export async function deleteScheduleRun(form: FormData): Promise<void> {
  await assertAdmin();
  const { error } = await db()
    .from("run_schedule")
    .delete()
    .eq("id", String(form.get("schedule_id")));
  // Saying nothing is how a Remove button that removes nothing goes unnoticed.
  if (error) throw new Error(`Could not remove that day: ${error.message}`);

  // The runs it already opened go with it, or Friday is off the schedule and
  // still on the shop, which is what "I deleted it and it is still there"
  // turned out to mean. Only ones still to come, and only while nothing has
  // been ordered on them: a run somebody has paid into is never swept away by
  // an edit to the week.
  const weekday = Number(form.get("weekday"));
  const slot = String(form.get("slot") ?? "");
  if (Number.isInteger(weekday) && slot) {
    const { data: rows } = await db()
      .from("batches")
      .select("id, run_date")
      .eq("slot", slot)
      .gte("run_date", lagosToday());

    // Midday UTC, so the day cannot slip either side of midnight.
    const sameDay = ((rows ?? []) as { id: string; run_date: string }[]).filter(
      (row) => new Date(`${row.run_date}T12:00:00Z`).getUTCDay() === weekday
    );

    if (sameDay.length > 0) {
      const ids = sameDay.map((row) => row.id);
      const { data: taken } = await db()
        .from("orders")
        .select("batch_id")
        .in("batch_id", ids);
      const busy = new Set((taken ?? []).map((row) => row.batch_id as string));
      const empty = ids.filter((id) => !busy.has(id));
      if (empty.length > 0) await db().from("batches").delete().in("id", empty);
    }
  }

  revalidatePath("/admin", "layout");
}

export async function toggleScheduleRun(form: FormData): Promise<void> {
  await assertAdmin();
  const { error } = await db()
    .from("run_schedule")
    .update({ active: form.get("next_active") === "true" })
    .eq("id", String(form.get("schedule_id")));
  if (error) throw new Error(`Could not change that day: ${error.message}`);
  revalidatePath("/admin", "layout");
}

/**
 * Opens every run the schedule calls for, up to the horizon. It happens on its
 * own whenever admin is opened; this is the button for when a schedule has
 * just changed and the runs should appear now.
 */
export async function generateRuns(form: FormData): Promise<void> {
  await assertAdmin();

  // A month at a time, because that is how somebody plans a term: "October is
  // open" is a thing you can hold in your head, "the next 21 days" is not.
  const month = String(form.get("month") ?? "").trim();
  if (/^\d{4}-\d{2}$/.test(month)) {
    const [year, index] = month.split("-").map(Number);
    const last = new Date(Date.UTC(year, index, 0)).getUTCDate();
    await openRunsBetween(`${month}-01`, `${month}-${String(last).padStart(2, "0")}`);
  } else {
    await ensureUpcomingBatches();
  }

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** Orders on a run that still count. A refunded one is not a reason to keep it. */
async function orderCount(batchId: string): Promise<number> {
  const { count } = await db()
    .from("orders")
    .select("id", { count: "exact", head: true })
    .eq("batch_id", batchId)
    .neq("status", "refunded");
  return count ?? 0;
}

/**
 * Removes a run entirely. Only ever an empty one: a run with orders on it is
 * somebody's dinner and a row in the books, so that is cancelled instead.
 */
export async function deleteRun(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("batch_id"));
  if ((await orderCount(id)) > 0) return;

  const { data: batch } = await db()
    .from("batches")
    .select("run_date, slot, kind")
    .eq("id", id)
    .maybeSingle();

  await db().from("carts").delete().eq("batch_id", id);
  await db().from("orders").delete().eq("batch_id", id);
  // A group that never became an order still points at this car, and a car
  // cannot be deleted while anything points at it. That is why deleting one
  // of these looked like it had worked and changed nothing.
  await clearDeadGroups(id);

  // A run the schedule still calls for comes straight back: opening admin
  // makes every run the week is supposed to have, and a deleted row is just a
  // missing one. Deleting it again, and again, is the same fight every time.
  //
  // So a scheduled run is cancelled instead. Cancelled it still exists, which
  // is what stops it being made again, and it takes no orders. To stop the day
  // itself, turn the weekday off in the schedule.
  const scheduled =
    batch && batch.kind !== "same_day"
      ? (await runSchedule(true)).some(
          (entry) =>
            entry.active &&
            entry.slot === batch.slot &&
            entry.weekday === new Date(`${batch.run_date}T12:00:00Z`).getUTCDay()
        )
      : false;

  if (scheduled) {
    await db().from("batches").update({ status: "cancelled" }).eq("id", id);
  } else {
    const { error } = await db().from("batches").delete().eq("id", id);
    // Silence here is what made this a fight nobody could win: the page came
    // back looking exactly as it did, with the run still on it and nothing
    // anywhere saying why.
    if (error) throw new Error(`Could not delete that run: ${error.message}`);
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/");
  redirect("/admin/runs");
}

/** A real capacity cap. Only set this when the car genuinely fills up. */
/**
 * Close the books on a run.
 *
 * Checked again here rather than trusted from the page: the page can be old,
 * and a run settled with money still outstanding is a run nobody will think
 * to look at again.
 */
export async function settleRun(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("batch_id"));

  const sheet = await batchSheet(id);
  if (!sheet) return;

  const open = stillOpen(sheet);
  if (open.length > 0) {
    throw new Error(`That run is not finished: ${open.join(" ")}`);
  }

  // A run where nothing was typed at the counter is either a run that cost
  // exactly the menu price or one nobody checked, and the difference is
  // money. Somebody has to say which.
  if (
    sheet.summary.reconciled.lines === 0 &&
    sheet.summary.reconciled.of > 0 &&
    form.get("counter_checked") !== "on"
  ) {
    throw new Error(
      "Nothing was typed at the counter on that run. Say the prices were the menu prices first."
    );
  }

  await db()
    .from("batches")
    .update({ settled_at: new Date().toISOString() })
    .eq("id", id);

  revalidatePath("/admin", "layout");
}

/** Something was wrong after all, so it goes back to being work. */
export async function reopenRun(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("batches")
    .update({ settled_at: null })
    .eq("id", String(form.get("batch_id")));

  revalidatePath("/admin", "layout");
}

export async function setBatchCapacity(form: FormData): Promise<void> {
  await assertAdmin();
  const raw = String(form.get("capacity") ?? "").trim();
  const capacity = raw === "" ? null : Number(raw);

  await db()
    .from("batches")
    .update({ capacity: Number.isFinite(capacity as number) ? capacity : null })
    .eq("id", String(form.get("batch_id")));
  revalidatePath("/admin", "layout");
}

export async function updateMenuItem(form: FormData): Promise<void> {
  await assertAdmin();
  const price = Number(form.get("price_food"));
  if (!Number.isFinite(price) || price < 0) return;

  await db()
    .from("menu_items")
    .update({
      price_food: Math.round(price),
      available: form.get("available") === "on",
      name: String(form.get("name") ?? "").trim() || undefined,
      description: String(form.get("description") ?? "").trim(),
      // A new photo wins; otherwise whatever link is in the box stays.
      image_url:
        (await uploadImage(fileFrom(form, "photo"), "items")) ??
        String(form.get("image_url") ?? "").trim(),
      category_id: String(form.get("category_id") ?? "") || null,
    })
    .eq("id", String(form.get("item_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function addMenuItem(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  const price = Number(form.get("price_food"));
  if (!name || !Number.isFinite(price) || price < 0) return;

  await db().from("menu_items").insert({
    restaurant_id: String(form.get("restaurant_id")),
    category_id: String(form.get("category_id") ?? "") || null,
    name,
    price_food: Math.round(price),
    description: String(form.get("description") ?? "").trim(),
    image_url:
      (await uploadImage(fileFrom(form, "photo"), "items")) ??
      String(form.get("image_url") ?? "").trim(),
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * One item with its choices, saved in a single go: an item on its own was
 * never the whole product. `groups` is JSON from the builder form, so sizes,
 * crusts and extras land with the item rather than in a second visit.
 */
export async function createFullItem(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  const price = Number(form.get("price_food"));
  const restaurantId = String(form.get("restaurant_id"));
  if (!name || !Number.isFinite(price) || price < 0) return;

  const { data: item } = await db()
    .from("menu_items")
    .insert({
      restaurant_id: restaurantId,
      category_id: String(form.get("category_id") ?? "") || null,
      name,
      price_food: Math.round(price),
      description: String(form.get("description") ?? "").trim(),
      image_url:
        (await uploadImage(fileFrom(form, "photo"), "items")) ??
        String(form.get("image_url") ?? "").trim(),
      sort_order: 100,
    })
    .select("id")
    .single();
  if (!item) return;

  await saveGroups(item.id as string, String(form.get("groups") ?? "[]"));

  revalidatePath("/admin", "layout");
  revalidatePath("/");
  redirect(`/admin/menu/${restaurantId}`);
}

type GroupDraft = {
  name: string;
  required: boolean;
  maxSelect: number;
  options: { name: string; priceDelta: number }[];
};

/** Writes a builder's option groups onto an item, in the order they were typed. */
async function saveGroups(itemId: string, json: string): Promise<void> {
  let groups: GroupDraft[] = [];
  try {
    groups = JSON.parse(json) as GroupDraft[];
  } catch {
    return; // A malformed draft is not worth failing the item over.
  }

  for (const [index, group] of groups.entries()) {
    const groupName = String(group.name ?? "").trim();
    if (!groupName) continue;

    const { data: saved } = await db()
      .from("item_option_groups")
      .insert({
        menu_item_id: itemId,
        name: groupName,
        required: Boolean(group.required),
        max_select: Math.max(1, Number(group.maxSelect) || 1),
        sort_order: index * 10,
      })
      .select("id")
      .single();
    if (!saved) continue;

    const options = (group.options ?? [])
      .map((option, position) => ({
        group_id: saved.id as string,
        name: String(option.name ?? "").trim(),
        price_delta: Math.round(Number(option.priceDelta) || 0),
        sort_order: position * 10,
      }))
      .filter((option) => option.name.length > 0);

    if (options.length > 0) await db().from("item_options").insert(options);
  }
}

/** Adds choices to an item that already exists, from the same builder. */
export async function addGroupsToItem(form: FormData): Promise<void> {
  await assertAdmin();
  await saveGroups(String(form.get("item_id")), String(form.get("groups") ?? "[]"));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** The delivery blocks a customer can pick from. */
export async function addHostel(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db()
    .from("hostels")
    .upsert(
      {
        name,
        note: String(form.get("note") ?? "").trim(),
        sort_order: Math.round(Number(form.get("sort_order") ?? 100)) || 100,
        active: true,
      },
      { onConflict: "name" }
    );

  revalidatePath("/admin", "layout");
  revalidatePath("/checkout");
}

export async function toggleHostel(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("hostels")
    .update({ active: form.get("next_active") === "true" })
    .eq("id", String(form.get("hostel_id")));

  revalidatePath("/admin", "layout");
  revalidatePath("/checkout");
}

export async function deleteHostel(form: FormData): Promise<void> {
  await assertAdmin();
  // Orders keep the block they were placed with, as plain text, so removing a
  // hostel from the list never rewrites where an old order went.
  await db().from("hostels").delete().eq("id", String(form.get("hostel_id")));

  revalidatePath("/admin", "layout");
  revalidatePath("/checkout");
}

/** A note on one order, for the admin's own eyes. */
export async function saveOrderNote(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("orders")
    .update({ admin_note: String(form.get("admin_note") ?? "").trim() })
    .eq("id", String(form.get("order_id")));

  revalidatePath("/admin", "layout");
  }

/**
 * A customer made by hand, with no order behind them.
 *
 * A PIN normally arrives with somebody's first order, which is fine until you
 * need a working number and PIN for something that must not put food in a car:
 * an app reviewer who has to sign in and try the delete, or somebody who
 * orders by WhatsApp and wants to see their history on the site.
 *
 * It only ever creates. An existing customer is left exactly as they are,
 * because overwriting a real person's PIN from a form that looks like this is
 * how somebody loses access to their own orders.
 */
export async function addCustomer(form: FormData): Promise<void> {
  await assertAdmin();

  const phone = normalisePhone(String(form.get("phone") ?? ""));
  const name = String(form.get("name") ?? "").trim();
  if (!phone || name === "") return;

  const pin = String(form.get("pin") ?? "").trim();

  await db()
    .from("customers")
    .insert({
      phone,
      name,
      hostel: String(form.get("hostel") ?? "").trim(),
      // Four digits of their choosing, or one made the same way a first
      // order makes them.
      pin: /^\d{4}$/.test(pin) ? pin : newPin(),
    });

  revalidatePath("/admin/customers");
}

/** A note on a person, carried across every order they place. */
/**
 * A customer with nothing behind them, removed.
 *
 * Testing a checkout makes a customer, and a shop that has been tested a few
 * times has a list mostly of itself. Anybody who has ever ordered stays: the
 * orders point at the phone number, and a name and a PIN that vanish from
 * under a real order help nobody.
 */
export async function deleteCustomer(form: FormData): Promise<void> {
  await assertAdmin();
  const phone = String(form.get("phone"));
  if (!phone) return;

  const { count } = await db()
    .from("orders")
    .select("id", { count: "exact", head: true })
    .eq("customer_phone", phone);
  if ((count ?? 0) > 0) {
    throw new Error("That number has orders behind it, so it stays.");
  }

  // Their abandoned carts go too: a cart with nobody behind it is a row
  // nobody will ever chase.
  await db().from("carts").delete().eq("phone", phone);
  const { error } = await db().from("customers").delete().eq("phone", phone);
  if (error) throw new Error(`Could not delete that customer: ${error.message}`);

  revalidatePath("/admin", "layout");
}

export async function saveCustomerNote(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("customers")
    .update({ admin_note: String(form.get("admin_note") ?? "").trim() })
    .eq("phone", String(form.get("phone")));

  revalidatePath("/admin/customers");
}

/**
 * Closing a cart, with what came of it. Chasing someone who has already said
 * no is the thing this prevents, so the reason is kept rather than a bare
 * flag: it is also the only record of why the money never arrived.
 */
export async function closeCart(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("carts")
    .update({
      handled_at: new Date().toISOString(),
      handled_reason: String(form.get("reason") ?? "").trim().slice(0, 120),
    })
    .eq("id", String(form.get("cart_id")));

  revalidatePath("/admin", "layout");
}

/**
 * Gone for good, for the ones that were never a customer: a test, a tap on
 * your own phone while checking something. Closing keeps a cart and says what
 * came of it, which is right for a real person who did not pay. For a test
 * there is nothing to keep and it only makes the list harder to read.
 */
export async function deleteCart(form: FormData): Promise<void> {
  await assertAdmin();
  const { error } = await db()
    .from("carts")
    .delete()
    .eq("id", String(form.get("cart_id")));
  if (error) throw new Error(`Could not delete that cart: ${error.message}`);

  revalidatePath("/admin", "layout");
}

/** Every cart already closed, cleared out in one go. */
export async function deleteClosedCarts(): Promise<void> {
  await assertAdmin();
  const { error } = await db()
    .from("carts")
    .delete()
    .not("handled_at", "is", null);
  if (error) throw new Error(`Could not clear those: ${error.message}`);

  revalidatePath("/admin", "layout");
}

/**
 * Make a link somebody can order off.
 *
 * A basket picked by hand: "I am going to Domino's, the meatball pizza is on
 * offer, here is a link." The food is fixed here and the price is not, because
 * prices live on the menu and a link that carried its own would disagree with
 * the shop the moment anything moved.
 */
export async function saveLink(form: FormData): Promise<{ ok: boolean; error?: string }> {
  await assertAdmin();

  const items = form.getAll("item_id").map(String).filter(Boolean);
  const lines = items.map((id) => ({
    menu_item_id: id,
    qty: Math.max(1, Number(form.get(`qty_${id}`) ?? 1)),
    // The size, the flavour: everything that moves the price, settled when
    // the link was made. Priced on the server like any other order.
    option_ids: String(form.get(`options_${id}`) ?? "")
      .split(",")
      .map((one) => one.trim())
      .filter(Boolean),
  }));

  const when = String(form.get("when") ?? "");
  const fee = String(form.get("fee") ?? "").trim();

  const result = await saveCheckoutLink({
    id: String(form.get("link_id") ?? "") || undefined,
    label: String(form.get("label") ?? ""),
    lines,
    // One control, two kinds of answer: a run is its id behind a marker, a
    // time is the instant itself, exactly as the group form does it.
    batchId: when.startsWith("run:") ? when.slice(4) : null,
    deliverAt: when.startsWith("run:") || when === "" ? null : when,
    // Empty means the ordinary rules, which is not the same as nought.
    fee: fee === "" ? null : Math.max(0, Math.round(Number(fee))),
    couponCode: String(form.get("coupon") ?? "").trim().toUpperCase() || null,
    paymentLink: String(form.get("payment_link") ?? ""),
    note: String(form.get("note") ?? ""),
  });

  revalidatePath("/admin", "layout");
  return result.ok ? { ok: true } : { ok: false, error: result.error };
}

export async function stopLink(form: FormData): Promise<void> {
  await assertAdmin();
  await setCheckoutLinkActive(String(form.get("link_id")), false);
  revalidatePath("/admin", "layout");
}

export async function startLink(form: FormData): Promise<void> {
  await assertAdmin();
  await setCheckoutLinkActive(String(form.get("link_id")), true);
  revalidatePath("/admin", "layout");
}

export async function removeLink(form: FormData): Promise<void> {
  await assertAdmin();
  await deleteCheckoutLink(String(form.get("link_id")));
  revalidatePath("/admin", "layout");
}

/**
 * Close a shared delivery from this side.
 *
 * The clock is the usual way, and whoever is looking at the board is the
 * second. Neither helps when the leader has shut their phone and the rest are
 * waiting on a car nobody is going to close. This prices it now and turns
 * every seat that has food and a number into an ordinary order.
 */
export async function closeGroupNow(
  form: FormData
): Promise<{ ok: boolean; error?: string }> {
  await assertAdmin();
  const id = String(form.get("group_id"));

  // Finalising food and giving a number are two steps, and closing between
  // them orders nothing: the seats cannot travel, so the group shuts with
  // nobody in it and everybody has to come back and fill their details in.
  // Better to say so than to do it.
  // Said rather than thrown. A throw here took the whole page down to the
  // error screen, which tells somebody standing in a kitchen nothing about
  // what to do next.
  const seats = await groupCarts(id);
  if (seats.length > 0 && !seats.some(canTravel)) {
    return {
      ok: false,
      error:
        "Nobody in that group has given a number and a block yet, so closing " +
        "it would order nothing. Leave it to the clock, or ask them to finish.",
    };
  }

  const result = await closeGroup(id);
  if (!result.ok) return { ok: false, error: result.error };

  revalidatePath("/admin", "layout");
  return { ok: true };
}

/**
 * Shut a group without ordering any of it.
 *
 * For a link nobody used, or a car that was a test. The seats go with it,
 * because food left behind in a closed group is food somebody is still
 * waiting for. Nobody is charged and nothing is bought.
 */
export async function cancelGroup(
  form: FormData
): Promise<{ ok: boolean; error?: string }> {
  await assertAdmin();
  const id = String(form.get("group_id"));

  const seats = await db().from("group_carts").delete().eq("group_id", id);
  if (seats.error) {
    return { ok: false, error: `Could not clear those seats: ${seats.error.message}` };
  }

  const { error } = await db()
    .from("order_groups")
    .update({ closed_at: new Date().toISOString() })
    .eq("id", id)
    .is("closed_at", null);
  if (error) return { ok: false, error: `Could not cancel that group: ${error.message}` };

  revalidatePath("/admin", "layout");
  return { ok: true };
}

/** Closed by mistake, or they came back. It goes back on the list. */
export async function reopenCart(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("carts")
    .update({ handled_at: null, handled_reason: "" })
    .eq("id", String(form.get("cart_id")));

  revalidatePath("/admin", "layout");
}

/** Money actually handed to a promoter, so "owed" means what is still owed. */
export async function recordPayout(form: FormData): Promise<void> {
  await assertAdmin();
  const amount = Math.round(Number(form.get("amount") ?? 0));
  if (!Number.isFinite(amount) || amount <= 0) return;

  const { error } = await db().from("promoter_payouts").insert({
    promoter_code: String(form.get("code")),
    amount,
    note: String(form.get("note") ?? "").trim(),
    // Which run it settles. Left empty for a payment covering several.
    batch_id: String(form.get("batch_id") ?? "") || null,
  });
  if (error) {
    throw new Error(
      `Could not record that: ${error.message}. ` +
        "If it mentions a column, run supabase/promoter_setup.sql in Supabase."
    );
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/promoter");
}

/** A slide on the home page: words, a picture, and where the button goes. */
export async function saveSlide(form: FormData): Promise<void> {
  await assertAdmin();
  const headline = String(form.get("headline") ?? "").trim();
  if (!headline) return;

  const id = String(form.get("slide_id") ?? "").trim();
  const row = {
    headline,
    body: String(form.get("body") ?? "").trim(),
    image_url:
      (await uploadImage(fileFrom(form, "photo"), "slides")) ??
      String(form.get("image_url") ?? "").trim(),
    link_url: String(form.get("link_url") ?? "").trim(),
    link_text: String(form.get("link_text") ?? "").trim(),
    sort_order: Math.round(Number(form.get("sort_order") ?? 100)) || 100,
    active: form.get("active") === "on",
  };

  if (id) await db().from("slides").update(row).eq("id", id);
  else await db().from("slides").insert(row);

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function deleteSlide(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("slides").delete().eq("id", String(form.get("slide_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** A discount code: what it takes off, and how long it lasts. */
/**
 * Ticked choices, as one set per question the dish asks.
 *
 * They arrive as "Size::Medium 12\"", because the question is what decides
 * whether two of them are alternatives or conditions. Within a question any
 * will do; across questions all must hold.
 */
function choiceJson(values: string[]): string {
  // The question is kept alongside the answer, not thrown away: without it
  // the picker cannot put its own ticks back, and BBQ Chicken means one thing
  // under First half and another under Second half.
  const sets = new Map<string, string[]>();
  for (const value of values) {
    const raw = value.trim();
    if (raw === "" || raw.endsWith("::")) continue;
    const group = raw.includes("::") ? raw.slice(0, raw.indexOf("::")) : "";
    sets.set(group, [...(sets.get(group) ?? []), raw]);
  }
  return sets.size === 0 ? "" : JSON.stringify([...sets.values()]);
}

export async function saveCoupon(form: FormData): Promise<void> {
  await assertAdmin();
  const code = String(form.get("code") ?? "").trim().toUpperCase();
  const amount = Math.round(Number(form.get("amount") ?? 0));
  // Nothing is a real answer now: free delivery is a fee of nothing. It is
  // only allowed where the offer sets the fee, so a code cannot be saved as
  // taking nothing off.
  const sets = form.get("applies_to") === "fee";
  // The whole offer was on screen, so a box left empty is an answer rather
  // than a question that was never asked.
  const whole = form.get("editing") === "1" || form.has("applies_to");
  if (!code || !Number.isFinite(amount) || amount < 0) return;
  if (amount === 0 && !sets) return;

  const expires = String(form.get("expires_at") ?? "").trim();
  const maxUses = Math.round(Number(form.get("max_uses") ?? 0));

  const effect = String(form.get("applies_to") ?? "delivery");
  const included = Math.round(Number(form.get("included_items") ?? 0));
  const perItem = Math.round(Number(form.get("extra_per_item") ?? 0));

  await db().from("coupons").upsert({
    code,
    applies_to: effect === "order" || effect === "fee" ? effect : "delivery",
    amount,
    // A promotion applies itself; a code is typed. Nothing else about them
    // differs, which is why they live in one table.
    automatic: effect === "fee",
    included_items: Number.isFinite(included) && included > 0 ? included : null,
    extra_per_item: Number.isFinite(perItem) && perItem > 0 ? perItem : 0,
    min_per_person: (() => {
      const floor = Math.round(Number(form.get("min_per_person") ?? 0));
      return Number.isFinite(floor) && floor > 0 ? floor : 0;
    })(),
    // Whether it reaches a car somebody has to themselves at all. Off by
    // default: a flat price built for a shared run does not cover one trip
    // for one person.
    same_day: form.get("same_day") === "on",
    // A size, by the name of the option on the dish, grouped by the question
    // it answers: Medium and two BBQ flavours is a medium and one of those
    // two, not any of three.
    required_choice: choiceJson(form.getAll("required_choice").map(String)),
    note: String(form.get("note") ?? "").trim(),
    active: form.get("active") === "on",
    // Blank means no limit, which is the normal case for a code in a group.
    expires_at: expires ? new Date(`${expires}T23:59:59+01:00`).toISOString() : null,
    max_uses: Number.isFinite(maxUses) && maxUses > 0 ? maxUses : null,
    first_order_only: form.get("first_order_only") === "on",
  });

  // Everything the offer covers, written on the same save as the offer
  // itself. It used to be four forms with four buttons, so filling in three
  // things and pressing one of them threw the other two away.
  //
  // Empty clears, which is how "any run" and "anywhere" are said. That only
  // holds when the whole form was on screen: creating one leaves alone what
  // it never showed.
  const runs = form.getAll("batch_id").map(String).filter(Boolean);
  if (whole || runs.length > 0) {
    await db().from("coupon_runs").delete().eq("coupon_code", code);
    if (runs.length > 0) {
      await db()
        .from("coupon_runs")
        .insert(runs.map((batch_id) => ({ coupon_code: code, batch_id })));
    }
  }

  const places = form.getAll("restaurant_id").map(String).filter(Boolean);
  if (whole || places.length > 0) await writeCouponPlaces(code, places);

  const dishes = form.getAll("menu_item_id").map(String).filter(Boolean);
  if (whole || dishes.length > 0) await writeCouponItems(code, dishes);

  const sections = form.getAll("category_id").map(String).filter(Boolean);
  if (whole || sections.length > 0) await writeCouponCategories(code, sections);

  revalidatePath("/admin", "layout");
}





async function writeCouponCategories(code: string, sections: string[]): Promise<void> {
  await db().from("coupon_categories").delete().eq("coupon_code", code);
  if (sections.length > 0) {
    await db()
      .from("coupon_categories")
      .insert(sections.map((category_id) => ({ coupon_code: code, category_id })));
  }
}

async function writeCouponItems(code: string, dishes: string[]): Promise<void> {
  await db().from("coupon_items").delete().eq("coupon_code", code);
  if (dishes.length > 0) {
    await db()
      .from("coupon_items")
      .insert(dishes.map((menu_item_id) => ({ coupon_code: code, menu_item_id })));
  }
}

async function writeCouponPlaces(code: string, places: string[]): Promise<void> {
  await db().from("coupon_restaurants").delete().eq("coupon_code", code);
  if (places.length > 0) {
    await db()
      .from("coupon_restaurants")
      .insert(places.map((restaurant_id) => ({ coupon_code: code, restaurant_id })));
  }
}


export async function toggleCoupon(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("coupons")
    .update({ active: form.get("next_active") === "true" })
    .eq("code", String(form.get("code")));
  revalidatePath("/admin", "layout");
}

export async function deleteCoupon(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("coupons").delete().eq("code", String(form.get("code")));
  revalidatePath("/admin", "layout");
}

export async function savePromoter(form: FormData): Promise<void> {
  await assertAdmin();
  const code = String(form.get("code") ?? "").trim().toUpperCase();
  if (!code) return;

  // A new promoter gets a PIN straight away, and an existing one keeps
  // theirs, since it may already be in their WhatsApp. Typing one over the
  // top wins, for when they have forgotten it.
  const { data: existing } = await db()
    .from("promoters")
    .select("pin")
    .eq("code", code)
    .maybeSingle();

  const typedPin = String(form.get("pin") ?? "").replace(/\D/g, "").slice(0, 4);

  const { error } = await db().from("promoters").upsert({
    code,
    name: String(form.get("name") ?? "").trim(),
    phone: String(form.get("phone") ?? "").trim(),
    rate: Math.round(Number(form.get("rate")) || 500),
    active: form.get("active") === "on",
    pin: typedPin || (existing?.pin as string) || newPin(),
  });

  // A save that quietly does nothing is worse than one that fails loudly:
  // the form comes back empty and reads as the data being wiped.
  if (error) {
    throw new Error(
      `Could not save the promoter: ${error.message}. ` +
        "If it mentions a column, run supabase/update.sql in Supabase."
    );
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/promoter");
}

/**
 * Settings are saved section by section, so only the fields a form actually
 * posts are written. Anything left out keeps its current value instead of
 * being blanked by a form that never showed it.
 */
const SETTING_FIELDS = [
  "bank_name",
  "bank_account_name",
  "bank_account_number",
  "whatsapp_number",
  "card_note",
  "instagram_handle",
  "whatsapp_group_link",
  "pitch_line",
  "product_notes",
  "footer_line",
  "msg_confirmed",
  "msg_payment",
  "msg_card",
  "msg_pin",
  "msg_ready",
  "msg_late",
  "msg_review",
  "paid_note",
  "fee_bands",
  "same_day_bands",
  "same_day_urgent_extra",
  "same_day_on",
  "same_day_first_hour",
  "same_day_last_hour",
  "same_day_day_hours",
  "admin_emails",
  "abandon_minutes",
  "window_afternoon",
  "window_night",
  "window_afternoon_from",
  "window_afternoon_to",
  "window_night_from",
  "window_night_to",
  "order_horizon_days",
  "tagline",
  "hide_promoter_link",
  "hide_footer",
  "ribbon_text",
  "offer_code",
  "auto_headline",
  "auto_lines",
] as const;

export async function saveSettings(form: FormData): Promise<void> {
  await assertAdmin();

  const patch: Record<string, string> = {};
  for (const field of SETTING_FIELDS) {
    const value = form.get(field);
    if (value !== null) patch[field] = String(value).trim();
  }
  if (Object.keys(patch).length === 0) return;

  const write = (fields: Record<string, string>) =>
    db()
      .from("settings")
      .update({ ...fields, updated_at: new Date().toISOString() })
      .eq("id", true);

  let { error } = await write(patch);

  // One column the database has not been given yet rejects the whole update,
  // so a newly added setting took every other setting on the form down with
  // it: changing the delivery hours did nothing, silently, and came back
  // showing the old ones. The unknown column is dropped and the rest saved,
  // and what did not save is said out loud rather than guessed at.
  const missing: string[] = [];
  while (error && missing.length < SETTING_FIELDS.length) {
    const named = SETTING_FIELDS.find(
      (field) => field in patch && error!.message.includes(field)
    );
    if (!named) break;

    missing.push(named);
    delete patch[named];
    if (Object.keys(patch).length === 0) break;
    ({ error } = await write(patch));
  }

  // A setting that saves to nowhere looks exactly like one that will not
  // stick, and you would have no way to tell which.
  if (error) {
    throw new Error(
      `Could not save that: ${error.message}. ` +
        "If it mentions a column, run supabase/update.sql in Supabase."
    );
  }
  if (missing.length > 0) {
    throw new Error(
      `Saved everything except ${missing.join(", ")}: the database has not got ` +
        "that column yet. Run supabase/update.sql in Supabase and save again."
    );
  }

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * A flash fee drop on one batch. Blank clears it. The reason is shown to
 * customers, because a bare cut reads as an admission that the normal fee was
 * always too high (addendum §4).
 */
export async function setFlashFee(form: FormData): Promise<void> {
  await assertAdmin();
  const raw = String(form.get("flash_fee") ?? "").trim();
  const fee = raw === "" ? null : Math.round(Number(raw));

  await db()
    .from("batches")
    .update({
      flash_fee: fee !== null && Number.isFinite(fee) && fee >= 0 ? fee : null,
      flash_fee_reason: String(form.get("flash_fee_reason") ?? "").trim(),
    })
    .eq("id", String(form.get("batch_id")));

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * One tap per stage of the run, shared by everyone in the batch. This is the
 * whole of tracking: no rider app, no GPS, nothing to go wrong on the road.
 */
export async function setBatchStage(form: FormData): Promise<void> {
  await assertAdmin();
  const stage = String(form.get("stage"));
  if (!STAGES.includes(stage as BatchStage)) return;

  // A stage says where the food is; a status says whether the shop is still
  // taking orders for it. Keeping the two in step by hand was busywork nobody
  // should have to remember, so a stage tap carries the status with it.
  const status =
    stage === "ordering"
      ? "open"
      : stage === "handed_out"
        ? "delivered"
        : "closed";

  const batchId = String(form.get("batch_id"));

  await db()
    .from("batches")
    .update({ stage, status, stage_updated_at: new Date().toISOString() })
    .eq("id", batchId);

  // The two stages a customer is actually waiting for. Told once, to the
  // people on that run who have paid and have the app, and never awaited: a
  // notification must not hold up the tap that moves a run along.
  if (stage === "on_the_road" || stage === "at_drop") {
    void (async () => {
      try {
        const { data } = await db()
          .from("orders")
          .select("customer_phone")
          .eq("batch_id", batchId)
          .neq("status", "pending")
          .neq("status", "refunded");

        const phones = [
          ...new Set(((data ?? []) as { customer_phone: string }[]).map((row) => row.customer_phone)),
        ];

        for (const phone of phones) {
          await pushToPhone(phone, {
            title: stage === "on_the_road" ? "On the road to you" : "We are at your hostel",
            body:
              stage === "on_the_road"
                ? "Your food has left the restaurants. Keep your phone near you."
                : "Come down when you are ready, or we will call you.",
          });
        }
      } catch {
        /* The run still moved on, which is the part that matters. */
      }
    })();
  }

  // Handed out means handed out: every paid order in the run is delivered,
  // rather than a run marked delivered sitting above twenty orders that still
  // read "paid". Anything unpaid is left alone, since it never travelled.
  if (stage === "handed_out") {
    await db()
      .from("orders")
      .update({ status: "delivered" })
      .eq("batch_id", batchId)
      .eq("status", "paid");
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/orders");
  revalidatePath("/o", "layout");
}

/** Restaurants are added and edited here, not only by running the seed file. */
export async function addRestaurant(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("restaurants").insert({
    name,
    address: String(form.get("address") ?? "").trim(),
    closes_at: String(form.get("closes_at") ?? "").trim() || "21:00",
    active: true,
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function updateRestaurant(form: FormData): Promise<void> {
  await assertAdmin();

  await db()
    .from("restaurants")
    .update({
      name: String(form.get("name") ?? "").trim() || undefined,
      address: String(form.get("address") ?? "").trim(),
      closes_at: String(form.get("closes_at") ?? "").trim() || undefined,
      logo_url:
        (await uploadImage(fileFrom(form, "logo"), "logos")) ??
        String(form.get("logo_url") ?? "").trim(),
      banner_url:
        (await uploadImage(fileFrom(form, "banner"), "banners")) ??
        String(form.get("banner_url") ?? "").trim(),
      // Off keeps a restaurant and its menu but takes it off the site, which is
      // how the brief adds Panarottis and the rest once the run is boring.
      active: form.get("active") === "on",
    })
    .eq("id", String(form.get("restaurant_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** The two launch restaurants and their menu, for a database with no seed. */
export async function seedLaunchRestaurants(): Promise<void> {
  await assertAdmin();

  const { data: existing } = await db().from("restaurants").select("id").limit(1);
  if (existing && existing.length > 0) return;

  const launch = [
    {
      name: "KFC Novare",
      address: "Novare Mall, Sangotedo",
      closes_at: "21:00",
      sort_order: 1,
      items: [
        ["Original Recipe 2pc + chips", 6500],
        ["8pc bucket", 18000],
        ["Wrap meal", 5500],
        ["Refuel Meal", 7000],
        ["Zinger burger meal", 8000],
      ] as const,
    },
    {
      name: "Domino's Pizza",
      address: "KM 34 Lekki-Epe Expy, Emperor Estate",
      closes_at: "22:00",
      sort_order: 2,
      items: [
        ["Medium pepperoni", 11000],
        ["Medium BBQ chicken", 12000],
        ["Large meat lovers", 17500],
        ["Chicken wings (6)", 6500],
        ["Garlic bread", 3000],
      ] as const,
    },
  ];

  for (const place of launch) {
    const { data: restaurant } = await db()
      .from("restaurants")
      .insert({
        name: place.name,
        address: place.address,
        closes_at: place.closes_at,
        active: true,
        sort_order: place.sort_order,
      })
      .select("id")
      .single();
    if (!restaurant) continue;

    await db().from("menu_items").insert(
      place.items.map(([name, price], index) => ({
        restaurant_id: restaurant.id,
        name,
        price_food: price,
        sort_order: index + 1,
      }))
    );
  }
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * A run on any day, at any cut-off. The automatic Friday batches cover the
 * usual week; this is for everything else, including exam-week late runs.
 */
export async function createBatch(form: FormData): Promise<void> {
  await assertAdmin();

  const runDate = String(form.get("run_date") ?? "").trim();
  const slot = String(form.get("slot") ?? "night");
  const time = String(form.get("cut_off_time") ?? "").trim();
  if (!runDate || !time) return;

  const [hour, minute] = time.split(":").map(Number);
  if (!Number.isFinite(hour) || !Number.isFinite(minute)) return;

  const fields = {
    run_date: runDate,
    slot,
    cut_off_at: lagosInstant(runDate, hour, minute),
    delivery_window_text:
      String(form.get("delivery_window_text") ?? "").trim() ||
      (await deliveryWindows())[slot as BatchSlot],
    status: "open",
    stage: "ordering",
  };

  // Found by hand rather than by ON CONFLICT, because (run_date, slot) is no
  // longer unique across every batch: a same day car borrows a run's date and
  // slot. Only a run is looked for, so editing Friday night never reaches
  // somebody's three o'clock car.
  const findRun = (byKind: boolean) => {
    const query = db()
      .from("batches")
      .select("id")
      .eq("run_date", runDate)
      .eq("slot", slot);
    return byKind ? query.neq("kind", "same_day").maybeSingle() : query.maybeSingle();
  };

  // Falls back when the database has not got `kind` yet, for the same reason
  // every other read of it does: a column that is not there must not stop
  // somebody editing a run.
  let { data: existingRun, error: findError } = await findRun(true);
  if (findError) ({ data: existingRun } = await findRun(false));

  if (existingRun) {
    await db().from("batches").update(fields).eq("id", existingRun.id as string);
  } else {
    await db().from("batches").insert(fields);
  }

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function addCategory(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("menu_categories").insert({
    restaurant_id: String(form.get("restaurant_id")),
    name,
    sort_order: Number(form.get("sort_order") ?? 100),
  });
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * Rename a category in place.
 *
 * Deleting one and adding it back would leave every item in it with no
 * category, so a name that is simply wrong needs a rename rather than a
 * round trip. The items keep their id, so nothing moves.
 */
export async function renameCategory(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  const id = String(form.get("category_id") ?? "");
  if (!name || !id) return;

  await db().from("menu_categories").update({ name }).eq("id", id);
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function deleteCategory(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("menu_categories").delete().eq("id", String(form.get("category_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** A choice on an item: Size, Flavour, Extras. */
export async function addOptionGroup(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("item_option_groups").insert({
    menu_item_id: String(form.get("item_id")),
    name,
    required: form.get("required") === "on",
    max_select: Math.max(1, Number(form.get("max_select") ?? 1)),
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function deleteOptionGroup(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("item_option_groups").delete().eq("id", String(form.get("group_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function addOption(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("item_options").insert({
    group_id: String(form.get("group_id")),
    name,
    price_delta: Math.round(Number(form.get("price_delta") ?? 0)) || 0,
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function updateOption(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("item_options")
    .update({
      name: String(form.get("name") ?? "").trim() || undefined,
      price_delta: Math.round(Number(form.get("price_delta") ?? 0)) || 0,
      available: form.get("available") === "on",
    })
    .eq("id", String(form.get("option_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function deleteOption(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("item_options").delete().eq("id", String(form.get("option_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

export async function deleteMenuItem(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("menu_items").delete().eq("id", String(form.get("item_id")));
  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * A whole menu in one paste. One item per line:
 *
 *   Category | Item name | Price | Description
 *
 * Category and description may be left out. Categories are created as they are
 * met, so a price list copied off a menu goes in without fifty separate forms.
 */
export async function importMenu(form: FormData): Promise<void> {
  await assertAdmin();

  const restaurantId = String(form.get("restaurant_id"));
  const text = String(form.get("menu_text") ?? "");
  if (!restaurantId || !text.trim()) return;

  const parsed = parseMenuText(text);
  if (parsed.length === 0) return;

  const { data: existing } = await db()
    .from("menu_categories")
    .select("id, name")
    .eq("restaurant_id", restaurantId);

  const categories = new Map(
    ((existing ?? []) as { id: string; name: string }[]).map((c) => [
      c.name.toLowerCase(),
      c.id,
    ])
  );

  let sort = 100;

  for (const item of parsed) {
    let categoryId: string | null = null;

    if (item.category) {
      const key = item.category.toLowerCase();
      if (!categories.has(key)) {
        const { data: created } = await db()
          .from("menu_categories")
          .insert({ restaurant_id: restaurantId, name: item.category, sort_order: sort })
          .select("id")
          .single();
        if (created) categories.set(key, created.id as string);
      }
      categoryId = categories.get(key) ?? null;
    }

    await db().from("menu_items").insert({
      restaurant_id: restaurantId,
      category_id: categoryId,
      name: item.name,
      price_food: item.price,
      description: item.description,
      // Unpriced or sold-out items are created but hidden, so nobody can order
      // a ₦0 pizza or something the shop has run out of.
      available: item.available && item.price > 0,
      sort_order: sort,
    });
    sort += 1;
  }

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * The same choice group on every item in a category. Fifteen pizzas each
 * needing Small, Medium and Large is not fifteen forms.
 */
export async function applyGroupToCategory(form: FormData): Promise<void> {
  await assertAdmin();

  const categoryId = String(form.get("category_id"));
  const groupName = String(form.get("group_name") ?? "").trim();
  const raw = String(form.get("options") ?? "").trim();
  if (!categoryId || !groupName || !raw) return;

  // "Small, Medium +2000, Large +5500"
  const options = raw
    .split(/[,\n]/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part, index) => {
      const match = part.match(/^(.*?)(?:\s*([+-]\s*[\d,.]+))?$/);
      const name = (match?.[1] ?? part).trim();
      const delta = match?.[2]
        ? Math.round(Number(match[2].replace(/[^\d.-]/g, "")))
        : 0;
      return { name, delta: Number.isFinite(delta) ? delta : 0, sort: index + 1 };
    })
    .filter((option) => option.name);

  const { data: items } = await db()
    .from("menu_items")
    .select("id")
    .eq("category_id", categoryId);

  for (const item of (items ?? []) as { id: string }[]) {
    const { data: existing } = await db()
      .from("item_option_groups")
      .select("id")
      .eq("menu_item_id", item.id)
      .eq("name", groupName)
      .maybeSingle();
    if (existing) continue;

    const { data: group } = await db()
      .from("item_option_groups")
      .insert({
        menu_item_id: item.id,
        name: groupName,
        required: form.get("required") === "on",
        max_select: Math.max(1, Number(form.get("max_select") ?? 1)),
        sort_order: 1,
      })
      .select("id")
      .single();
    if (!group) continue;

    await db().from("item_options").insert(
      options.map((option) => ({
        group_id: group.id,
        name: option.name,
        price_delta: option.delta,
        sort_order: option.sort,
      }))
    );
  }

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** One tap on and off, for the times a branch has run out mid-week. */
export async function toggleItemAvailable(form: FormData): Promise<void> {
  await assertAdmin();

  await db()
    .from("menu_items")
    .update({ available: form.get("available") === "true" })
    .eq("id", String(form.get("item_id")));

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/**
 * Move one row up or down a list that the customer sees.
 *
 * The whole list is renumbered rather than the two rows swapped, because a
 * seeded list is full of ties: everything arrives at sort_order 100 and a
 * swap between two hundreds changes nothing. Renumbering also means the
 * order you see in admin is the order that gets saved.
 */
async function shuffle(
  table: "restaurants" | "slides",
  id: string,
  direction: "up" | "down"
): Promise<void> {
  // Restaurants have no created_at, so ties break on the name instead.
  const tiebreak = table === "slides" ? "created_at" : "name";
  const { data } = await db()
    .from(table)
    .select("id")
    .order("sort_order")
    .order(tiebreak);

  const list = (data ?? []) as { id: string }[];
  const at = list.findIndex((row) => row.id === id);
  if (at < 0) return;

  const to = direction === "up" ? at - 1 : at + 1;
  if (to < 0 || to >= list.length) return;

  [list[at], list[to]] = [list[to], list[at]];

  await Promise.all(
    list.map((row, index) =>
      db().from(table).update({ sort_order: index + 1 }).eq("id", row.id)
    )
  );

  revalidatePath("/admin", "layout");
  updateTag("menu");
  revalidatePath("/", "layout");
}

/** Reorder the restaurant list, which is the order on the home page. */
export async function moveRestaurant(form: FormData): Promise<void> {
  await assertAdmin();
  await shuffle(
    "restaurants",
    String(form.get("restaurant_id")),
    form.get("direction") === "up" ? "up" : "down"
  );
}

/** Reorder the home page slider. */
export async function moveSlide(form: FormData): Promise<void> {
  await assertAdmin();
  await shuffle(
    "slides",
    String(form.get("slide_id")),
    form.get("direction") === "up" ? "up" : "down"
  );
}

/**
 * An account customers can pay into.
 *
 * Three accounts is not three times the choice: it is one account for most
 * people and a shorter, cheaper transfer for anyone who banks where you do.
 */
export async function addBankAccount(form: FormData): Promise<void> {
  await assertAdmin();
  const bank = String(form.get("bank_name") ?? "").trim();
  const number = String(form.get("account_number") ?? "").replace(/\D/g, "");
  if (!bank || number.length < 6) return;

  const { error } = await db().from("bank_accounts").insert({
    bank_name: bank,
    account_name: String(form.get("account_name") ?? "").trim(),
    account_number: number,
    sort_order: Number(form.get("sort_order")) || 100,
  });
  if (error) {
    throw new Error(
      `Could not add that account: ${error.message}. If it mentions ` +
        "bank_accounts, run supabase/update.sql."
    );
  }
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function toggleBankAccount(form: FormData): Promise<void> {
  await assertAdmin();
  const { error } = await db()
    .from("bank_accounts")
    .update({ active: form.get("next_active") === "true" })
    .eq("id", String(form.get("account_id")));
  if (error) throw new Error(`Could not change that account: ${error.message}`);
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function deleteBankAccount(form: FormData): Promise<void> {
  await assertAdmin();
  const { error } = await db()
    .from("bank_accounts")
    .delete()
    .eq("id", String(form.get("account_id")));
  if (error) throw new Error(`Could not remove that account: ${error.message}`);
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export type DealPushState = { error: string | null; sent: number | null };

/**
 * A notification to everybody who has the app and still wants to hear from us.
 *
 * Where it lands matters as much as what it says: "new deal at Domino's" that
 * opens the whole shop makes somebody do the finding themselves, which is the
 * moment most of them stop. So the destination is picked here, and travels
 * with the message.
 */
export async function sendDealPush(
  _prev: DealPushState,
  form: FormData
): Promise<DealPushState> {
  await assertAdmin();

  const title = String(form.get("title") ?? "").trim().slice(0, 80);
  const body = String(form.get("body") ?? "").trim().slice(0, 180);
  if (title.length < 3) return { error: "Give it a title.", sent: null };
  if (body.length < 3) return { error: "Give it a line of text.", sent: null };

  const restaurant = String(form.get("restaurant") ?? "").trim();
  const category = String(form.get("category") ?? "").trim();

  // Only ever one of ours, built here rather than typed, so a stray paste
  // cannot send everybody somewhere off the shop.
  const path = restaurant
    ? `/r/${restaurant}${category ? `?category=${category}` : ""}`
    : "/";

  const result = await pushDeal({ title, body, path });
  if (result.of === 0) {
    return { error: "No phone has the app with deals switched on yet.", sent: null };
  }

  revalidatePath("/admin/notifications");
  return { error: null, sent: result.sent };
}
