"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { isSignedIn, passwordMatches, signIn, signOut } from "@/lib/admin-auth";
import { db } from "@/lib/supabase";
import { STAGES, type BatchStage } from "@/lib/stages";
import { type BatchSlot } from "@/lib/config";
import { deliveryWindows, externalUrl } from "@/lib/settings";
import { lagosInstant } from "@/lib/time";
import { ensureUpcomingBatches, openRunsBetween } from "@/lib/batches";
import { fileFrom, uploadImage } from "@/lib/uploads";
import { parseMenuText } from "@/lib/menu-import";
import { newPin } from "@/lib/customer-auth";

async function assertAdmin(): Promise<void> {
  if (!(await isSignedIn())) throw new Error("Not signed in.");
}

export async function login(
  _prev: { error: string | null },
  form: FormData
): Promise<{ error: string | null }> {
  if (!passwordMatches(String(form.get("password") ?? ""))) {
    return { error: "Wrong password." };
  }
  await signIn();
  revalidatePath("/admin", "layout");
  return { error: null };
}

export async function logout(): Promise<void> {
  await signOut();
  revalidatePath("/admin", "layout");
}

/**
 * Manual "mark paid". The transfer is matched by the phone number in the
 * narration. This is replaced by a Paystack webhook once reconciliation stops
 * being trivial (brief §13), which is why payment_ref exists from day one.
 */
export async function markPaid(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("order_id"));
  const ref = String(form.get("payment_ref") ?? "").trim();

  await db()
    .from("orders")
    .update({
      status: "paid",
      paid_at: new Date().toISOString(),
      payment_ref: ref || null,
    })
    .eq("id", id);
  revalidatePath("/admin", "layout");
}

/**
 * The card link is generated by hand in a payment app and pasted here, so it
 * can be sent again without generating another one.
 */
export async function savePaymentLink(form: FormData): Promise<void> {
  await assertAdmin();
  // Stored with its scheme, so it is a link to somewhere else rather than a
  // path on this site.
  const link = externalUrl(String(form.get("payment_link") ?? ""));

  await db()
    .from("orders")
    .update({ payment_link: link })
    .eq("id", String(form.get("order_id")));

  revalidatePath("/admin", "layout");
  }

/**
 * Ticking a bag off marks everything in it delivered, and untricking it puts
 * it back to paid. The tick used to be a private checklist in the browser
 * that looked identical to the real thing, so a bag could be ticked all
 * evening while its customer's page still read "paid and on the run".
 */
export async function setBagDelivered(form: FormData): Promise<void> {
  await assertAdmin();
  const ids = String(form.get("order_ids") ?? "")
    .split(",")
    .map((id) => id.trim())
    .filter(Boolean);
  if (ids.length === 0) return;

  const delivered = form.get("delivered") === "true";
  await db()
    .from("orders")
    .update({ status: delivered ? "delivered" : "paid" })
    .in("id", ids);

  revalidatePath("/admin", "layout");
  revalidatePath("/orders");
  revalidatePath("/o", "layout");
}

export async function markDelivered(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("orders")
    .update({ status: "delivered" })
    .eq("id", String(form.get("order_id")));
  revalidatePath("/admin", "layout");
}

/** Refunds are same-night and in full. There are no partial refunds here. */
export async function refundOrder(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("orders")
    .update({ status: "refunded" })
    .eq("id", String(form.get("order_id")));
  revalidatePath("/admin", "layout");
}

export async function setBatchStatus(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("batches")
    .update({ status: String(form.get("status")) })
    .eq("id", String(form.get("batch_id")));
  revalidatePath("/admin", "layout");
}

/**
 * What the run cost to make. Typed in on the night, so the money tab can show
 * profit rather than "left before fuel and driver".
 */
export async function setRunCosts(form: FormData): Promise<void> {
  await assertAdmin();
  const money = (field: string) => {
    const value = Math.round(Number(form.get(field) ?? 0));
    return Number.isFinite(value) && value > 0 ? value : 0;
  };

  await db()
    .from("batches")
    .update({
      fuel_cost: money("fuel_cost"),
      driver_cost: money("driver_cost"),
      other_cost: money("other_cost"),
      cost_note: String(form.get("cost_note") ?? "").trim(),
    })
    .eq("id", String(form.get("batch_id")));

  revalidatePath("/admin", "layout");
}

/**
 * When a run lands and when it closes, changed after the run exists. A run
 * that slips by an hour has to be able to say so without being recreated.
 */
export async function updateRun(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("batch_id"));

  const { data: batch } = await db()
    .from("batches")
    .select("run_date, slot")
    .eq("id", id)
    .maybeSingle();
  if (!batch) return;

  const orders = await orderCount(id);
  // The day and the slot decide which orders belong where, so they only move
  // while the run is still empty. The window and the cut-off change any time.
  const runDate =
    orders === 0 && String(form.get("run_date") ?? "").trim()
      ? String(form.get("run_date")).trim()
      : (batch.run_date as string);
  const slot =
    orders === 0 && String(form.get("slot") ?? "")
      ? String(form.get("slot"))
      : (batch.slot as string);

  const patch: Record<string, string> = {
    run_date: runDate,
    slot,
    delivery_window_text: String(form.get("delivery_window_text") ?? "").trim(),
  };

  const time = String(form.get("cut_off_time") ?? "").trim();
  if (/^\d{2}:\d{2}$/.test(time)) {
    const [hour, minute] = time.split(":").map(Number);
    patch.cut_off_at = lagosInstant(runDate, hour, minute);
  }

  await db().from("batches").update(patch).eq("id", id);

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** One line of the weekly schedule: a day, a slot, a cut-off and a window. */
export async function saveScheduleRun(form: FormData): Promise<void> {
  await assertAdmin();
  const weekday = Number(form.get("weekday"));
  const slot = String(form.get("slot") ?? "afternoon");
  const cutOff = String(form.get("cut_off") ?? "").trim();
  if (!Number.isInteger(weekday) || weekday < 0 || weekday > 6) return;
  if (!/^\d{2}:\d{2}$/.test(cutOff)) return;

  await db()
    .from("run_schedule")
    .upsert(
      {
        weekday,
        slot,
        cut_off: cutOff,
        window_text: String(form.get("window_text") ?? "").trim(),
        active: true,
      },
      { onConflict: "weekday,slot" }
    );

  revalidatePath("/admin", "layout");
}

/**
 * Removes a day from the schedule. Runs already opened for it are left alone:
 * they are deleted one at a time, and only while nothing has been ordered.
 */
export async function deleteScheduleRun(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("run_schedule").delete().eq("id", String(form.get("schedule_id")));
  revalidatePath("/admin", "layout");
}

export async function toggleScheduleRun(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("run_schedule")
    .update({ active: form.get("active") === "true" })
    .eq("id", String(form.get("schedule_id")));
  revalidatePath("/admin", "layout");
}

/**
 * Opens every run the schedule calls for, up to the horizon. It happens on its
 * own whenever admin is opened; this is the button for when a schedule has
 * just changed and the runs should appear now.
 */
export async function generateRuns(form: FormData): Promise<void> {
  await assertAdmin();

  // A month at a time, because that is how somebody plans a term: "October is
  // open" is a thing you can hold in your head, "the next 21 days" is not.
  const month = String(form.get("month") ?? "").trim();
  if (/^\d{4}-\d{2}$/.test(month)) {
    const [year, index] = month.split("-").map(Number);
    const last = new Date(Date.UTC(year, index, 0)).getUTCDate();
    await openRunsBetween(`${month}-01`, `${month}-${String(last).padStart(2, "0")}`);
  } else {
    await ensureUpcomingBatches();
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** Orders on a run that still count. A refunded one is not a reason to keep it. */
async function orderCount(batchId: string): Promise<number> {
  const { count } = await db()
    .from("orders")
    .select("id", { count: "exact", head: true })
    .eq("batch_id", batchId)
    .neq("status", "refunded");
  return count ?? 0;
}

/**
 * Removes a run entirely. Only ever an empty one: a run with orders on it is
 * somebody's dinner and a row in the books, so that is cancelled instead.
 */
export async function deleteRun(form: FormData): Promise<void> {
  await assertAdmin();
  const id = String(form.get("batch_id"));
  if ((await orderCount(id)) > 0) return;

  await db().from("carts").delete().eq("batch_id", id);
  await db().from("orders").delete().eq("batch_id", id);
  await db().from("batches").delete().eq("id", id);

  revalidatePath("/admin", "layout");
  revalidatePath("/");
  redirect("/admin/runs");
}

/** A real capacity cap. Only set this when the car genuinely fills up. */
export async function setBatchCapacity(form: FormData): Promise<void> {
  await assertAdmin();
  const raw = String(form.get("capacity") ?? "").trim();
  const capacity = raw === "" ? null : Number(raw);

  await db()
    .from("batches")
    .update({ capacity: Number.isFinite(capacity as number) ? capacity : null })
    .eq("id", String(form.get("batch_id")));
  revalidatePath("/admin", "layout");
}

export async function updateMenuItem(form: FormData): Promise<void> {
  await assertAdmin();
  const price = Number(form.get("price_food"));
  if (!Number.isFinite(price) || price < 0) return;

  await db()
    .from("menu_items")
    .update({
      price_food: Math.round(price),
      available: form.get("available") === "on",
      name: String(form.get("name") ?? "").trim() || undefined,
      description: String(form.get("description") ?? "").trim(),
      // A new photo wins; otherwise whatever link is in the box stays.
      image_url:
        (await uploadImage(fileFrom(form, "photo"), "items")) ??
        String(form.get("image_url") ?? "").trim(),
      category_id: String(form.get("category_id") ?? "") || null,
    })
    .eq("id", String(form.get("item_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function addMenuItem(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  const price = Number(form.get("price_food"));
  if (!name || !Number.isFinite(price) || price < 0) return;

  await db().from("menu_items").insert({
    restaurant_id: String(form.get("restaurant_id")),
    category_id: String(form.get("category_id") ?? "") || null,
    name,
    price_food: Math.round(price),
    description: String(form.get("description") ?? "").trim(),
    image_url:
      (await uploadImage(fileFrom(form, "photo"), "items")) ??
      String(form.get("image_url") ?? "").trim(),
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * One item with its choices, saved in a single go: an item on its own was
 * never the whole product. `groups` is JSON from the builder form, so sizes,
 * crusts and extras land with the item rather than in a second visit.
 */
export async function createFullItem(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  const price = Number(form.get("price_food"));
  const restaurantId = String(form.get("restaurant_id"));
  if (!name || !Number.isFinite(price) || price < 0) return;

  const { data: item } = await db()
    .from("menu_items")
    .insert({
      restaurant_id: restaurantId,
      category_id: String(form.get("category_id") ?? "") || null,
      name,
      price_food: Math.round(price),
      description: String(form.get("description") ?? "").trim(),
      image_url:
        (await uploadImage(fileFrom(form, "photo"), "items")) ??
        String(form.get("image_url") ?? "").trim(),
      sort_order: 100,
    })
    .select("id")
    .single();
  if (!item) return;

  await saveGroups(item.id as string, String(form.get("groups") ?? "[]"));

  revalidatePath("/admin", "layout");
  revalidatePath("/");
  redirect(`/admin/menu/${restaurantId}`);
}

type GroupDraft = {
  name: string;
  required: boolean;
  maxSelect: number;
  options: { name: string; priceDelta: number }[];
};

/** Writes a builder's option groups onto an item, in the order they were typed. */
async function saveGroups(itemId: string, json: string): Promise<void> {
  let groups: GroupDraft[] = [];
  try {
    groups = JSON.parse(json) as GroupDraft[];
  } catch {
    return; // A malformed draft is not worth failing the item over.
  }

  for (const [index, group] of groups.entries()) {
    const groupName = String(group.name ?? "").trim();
    if (!groupName) continue;

    const { data: saved } = await db()
      .from("item_option_groups")
      .insert({
        menu_item_id: itemId,
        name: groupName,
        required: Boolean(group.required),
        max_select: Math.max(1, Number(group.maxSelect) || 1),
        sort_order: index * 10,
      })
      .select("id")
      .single();
    if (!saved) continue;

    const options = (group.options ?? [])
      .map((option, position) => ({
        group_id: saved.id as string,
        name: String(option.name ?? "").trim(),
        price_delta: Math.round(Number(option.priceDelta) || 0),
        sort_order: position * 10,
      }))
      .filter((option) => option.name.length > 0);

    if (options.length > 0) await db().from("item_options").insert(options);
  }
}

/** Adds choices to an item that already exists, from the same builder. */
export async function addGroupsToItem(form: FormData): Promise<void> {
  await assertAdmin();
  await saveGroups(String(form.get("item_id")), String(form.get("groups") ?? "[]"));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** The delivery blocks a customer can pick from. */
export async function addHostel(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db()
    .from("hostels")
    .upsert(
      {
        name,
        note: String(form.get("note") ?? "").trim(),
        sort_order: Math.round(Number(form.get("sort_order") ?? 100)) || 100,
        active: true,
      },
      { onConflict: "name" }
    );

  revalidatePath("/admin", "layout");
  revalidatePath("/checkout");
}

export async function toggleHostel(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("hostels")
    .update({ active: form.get("active") === "true" })
    .eq("id", String(form.get("hostel_id")));

  revalidatePath("/admin", "layout");
  revalidatePath("/checkout");
}

export async function deleteHostel(form: FormData): Promise<void> {
  await assertAdmin();
  // Orders keep the block they were placed with, as plain text, so removing a
  // hostel from the list never rewrites where an old order went.
  await db().from("hostels").delete().eq("id", String(form.get("hostel_id")));

  revalidatePath("/admin", "layout");
  revalidatePath("/checkout");
}

/** A note on one order, for the admin's own eyes. */
export async function saveOrderNote(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("orders")
    .update({ admin_note: String(form.get("admin_note") ?? "").trim() })
    .eq("id", String(form.get("order_id")));

  revalidatePath("/admin", "layout");
  }

/** A note on a person, carried across every order they place. */
export async function saveCustomerNote(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("customers")
    .update({ admin_note: String(form.get("admin_note") ?? "").trim() })
    .eq("phone", String(form.get("phone")));

  revalidatePath("/admin/customers");
}

/**
 * Closing a cart, with what came of it. Chasing someone who has already said
 * no is the thing this prevents, so the reason is kept rather than a bare
 * flag: it is also the only record of why the money never arrived.
 */
export async function closeCart(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("carts")
    .update({
      handled_at: new Date().toISOString(),
      handled_reason: String(form.get("reason") ?? "").trim().slice(0, 120),
    })
    .eq("id", String(form.get("cart_id")));

  revalidatePath("/admin", "layout");
}

/** Closed by mistake, or they came back. It goes back on the list. */
export async function reopenCart(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("carts")
    .update({ handled_at: null, handled_reason: "" })
    .eq("id", String(form.get("cart_id")));

  revalidatePath("/admin", "layout");
}

/** Money actually handed to a promoter, so "owed" means what is still owed. */
export async function recordPayout(form: FormData): Promise<void> {
  await assertAdmin();
  const amount = Math.round(Number(form.get("amount") ?? 0));
  if (!Number.isFinite(amount) || amount <= 0) return;

  await db().from("promoter_payouts").insert({
    promoter_code: String(form.get("code")),
    amount,
    note: String(form.get("note") ?? "").trim(),
  });

  revalidatePath("/admin", "layout");
  revalidatePath("/promoter");
}

/** A slide on the home page: words, a picture, and where the button goes. */
export async function saveSlide(form: FormData): Promise<void> {
  await assertAdmin();
  const headline = String(form.get("headline") ?? "").trim();
  if (!headline) return;

  const id = String(form.get("slide_id") ?? "").trim();
  const row = {
    headline,
    body: String(form.get("body") ?? "").trim(),
    image_url:
      (await uploadImage(fileFrom(form, "photo"), "slides")) ??
      String(form.get("image_url") ?? "").trim(),
    link_url: String(form.get("link_url") ?? "").trim(),
    link_text: String(form.get("link_text") ?? "").trim(),
    sort_order: Math.round(Number(form.get("sort_order") ?? 100)) || 100,
    active: form.get("active") === "on",
  };

  if (id) await db().from("slides").update(row).eq("id", id);
  else await db().from("slides").insert(row);

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function deleteSlide(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("slides").delete().eq("id", String(form.get("slide_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** A discount code: what it takes off, and how long it lasts. */
export async function saveCoupon(form: FormData): Promise<void> {
  await assertAdmin();
  const code = String(form.get("code") ?? "").trim().toUpperCase();
  const amount = Math.round(Number(form.get("amount") ?? 0));
  if (!code || !Number.isFinite(amount) || amount <= 0) return;

  const expires = String(form.get("expires_at") ?? "").trim();
  const maxUses = Math.round(Number(form.get("max_uses") ?? 0));

  await db().from("coupons").upsert({
    code,
    applies_to: form.get("applies_to") === "order" ? "order" : "delivery",
    amount,
    note: String(form.get("note") ?? "").trim(),
    active: form.get("active") === "on",
    // Blank means no limit, which is the normal case for a code in a group.
    expires_at: expires ? new Date(`${expires}T23:59:59+01:00`).toISOString() : null,
    max_uses: Number.isFinite(maxUses) && maxUses > 0 ? maxUses : null,
    first_order_only: form.get("first_order_only") === "on",
  });

  // Runs ticked while creating it, so a code made for Wednesday is kept to
  // Wednesday without a second save.
  const runs = form.getAll("batch_id").map(String).filter(Boolean);
  if (runs.length > 0) {
    await db().from("coupon_runs").delete().eq("coupon_code", code);
    await db()
      .from("coupon_runs")
      .insert(runs.map((batch_id) => ({ coupon_code: code, batch_id })));
  }

  revalidatePath("/admin", "layout");
}

/** Which runs a code works on. No runs picked means every run. */
export async function setCouponRuns(form: FormData): Promise<void> {
  await assertAdmin();
  const code = String(form.get("code"));
  const runs = form.getAll("batch_id").map(String).filter(Boolean);

  await db().from("coupon_runs").delete().eq("coupon_code", code);
  if (runs.length > 0) {
    await db()
      .from("coupon_runs")
      .insert(runs.map((batch_id) => ({ coupon_code: code, batch_id })));
  }

  revalidatePath("/admin", "layout");
}

export async function toggleCoupon(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("coupons")
    .update({ active: form.get("active") === "true" })
    .eq("code", String(form.get("code")));
  revalidatePath("/admin", "layout");
}

export async function deleteCoupon(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("coupons").delete().eq("code", String(form.get("code")));
  revalidatePath("/admin", "layout");
}

export async function savePromoter(form: FormData): Promise<void> {
  await assertAdmin();
  const code = String(form.get("code") ?? "").trim().toUpperCase();
  if (!code) return;

  // A new promoter gets a PIN straight away, and an existing one keeps
  // theirs, since it may already be in their WhatsApp. Typing one over the
  // top wins, for when they have forgotten it.
  const { data: existing } = await db()
    .from("promoters")
    .select("pin")
    .eq("code", code)
    .maybeSingle();

  const typedPin = String(form.get("pin") ?? "").replace(/\D/g, "").slice(0, 4);

  const { error } = await db().from("promoters").upsert({
    code,
    name: String(form.get("name") ?? "").trim(),
    phone: String(form.get("phone") ?? "").trim(),
    rate: Math.round(Number(form.get("rate")) || 500),
    active: form.get("active") === "on",
    pin: typedPin || (existing?.pin as string) || newPin(),
  });

  // A save that quietly does nothing is worse than one that fails loudly:
  // the form comes back empty and reads as the data being wiped.
  if (error) {
    throw new Error(
      `Could not save the promoter: ${error.message}. ` +
        "If it mentions a column, run supabase/update.sql in Supabase."
    );
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/promoter");
}

/**
 * Settings are saved section by section, so only the fields a form actually
 * posts are written. Anything left out keeps its current value instead of
 * being blanked by a form that never showed it.
 */
const SETTING_FIELDS = [
  "bank_name",
  "bank_account_name",
  "bank_account_number",
  "whatsapp_number",
  "card_note",
  "instagram_handle",
  "whatsapp_group_link",
  "pitch_line",
  "product_notes",
  "footer_line",
  "msg_confirmed",
  "msg_payment",
  "msg_card",
  "msg_pin",
  "msg_ready",
  "msg_late",
  "paid_note",
  "fee_bands",
  "admin_emails",
  "abandon_minutes",
  "window_afternoon",
  "window_night",
  "order_horizon_days",
  "tagline",
  "auto_headline",
  "auto_lines",
] as const;

export async function saveSettings(form: FormData): Promise<void> {
  await assertAdmin();

  const patch: Record<string, string> = {};
  for (const field of SETTING_FIELDS) {
    const value = form.get(field);
    if (value !== null) patch[field] = String(value).trim();
  }
  if (Object.keys(patch).length === 0) return;

  await db()
    .from("settings")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", true);

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * A flash fee drop on one batch. Blank clears it. The reason is shown to
 * customers, because a bare cut reads as an admission that the normal fee was
 * always too high (addendum §4).
 */
export async function setFlashFee(form: FormData): Promise<void> {
  await assertAdmin();
  const raw = String(form.get("flash_fee") ?? "").trim();
  const fee = raw === "" ? null : Math.round(Number(raw));

  await db()
    .from("batches")
    .update({
      flash_fee: fee !== null && Number.isFinite(fee) && fee >= 0 ? fee : null,
      flash_fee_reason: String(form.get("flash_fee_reason") ?? "").trim(),
    })
    .eq("id", String(form.get("batch_id")));

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * One tap per stage of the run, shared by everyone in the batch. This is the
 * whole of tracking: no rider app, no GPS, nothing to go wrong on the road.
 */
export async function setBatchStage(form: FormData): Promise<void> {
  await assertAdmin();
  const stage = String(form.get("stage"));
  if (!STAGES.includes(stage as BatchStage)) return;

  // A stage says where the food is; a status says whether the shop is still
  // taking orders for it. Keeping the two in step by hand was busywork nobody
  // should have to remember, so a stage tap carries the status with it.
  const status =
    stage === "ordering"
      ? "open"
      : stage === "handed_out"
        ? "delivered"
        : "closed";

  const batchId = String(form.get("batch_id"));

  await db()
    .from("batches")
    .update({ stage, status, stage_updated_at: new Date().toISOString() })
    .eq("id", batchId);

  // Handed out means handed out: every paid order in the run is delivered,
  // rather than a run marked delivered sitting above twenty orders that still
  // read "paid". Anything unpaid is left alone, since it never travelled.
  if (stage === "handed_out") {
    await db()
      .from("orders")
      .update({ status: "delivered" })
      .eq("batch_id", batchId)
      .eq("status", "paid");
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/orders");
  revalidatePath("/o", "layout");
}

/** Restaurants are added and edited here, not only by running the seed file. */
export async function addRestaurant(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("restaurants").insert({
    name,
    address: String(form.get("address") ?? "").trim(),
    closes_at: String(form.get("closes_at") ?? "").trim() || "21:00",
    active: true,
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function updateRestaurant(form: FormData): Promise<void> {
  await assertAdmin();

  await db()
    .from("restaurants")
    .update({
      name: String(form.get("name") ?? "").trim() || undefined,
      address: String(form.get("address") ?? "").trim(),
      closes_at: String(form.get("closes_at") ?? "").trim() || undefined,
      logo_url:
        (await uploadImage(fileFrom(form, "logo"), "logos")) ??
        String(form.get("logo_url") ?? "").trim(),
      banner_url:
        (await uploadImage(fileFrom(form, "banner"), "banners")) ??
        String(form.get("banner_url") ?? "").trim(),
      // Off keeps a restaurant and its menu but takes it off the site, which is
      // how the brief adds Panarottis and the rest once the run is boring.
      active: form.get("active") === "on",
    })
    .eq("id", String(form.get("restaurant_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** The two launch restaurants and their menu, for a database with no seed. */
export async function seedLaunchRestaurants(): Promise<void> {
  await assertAdmin();

  const { data: existing } = await db().from("restaurants").select("id").limit(1);
  if (existing && existing.length > 0) return;

  const launch = [
    {
      name: "KFC Novare",
      address: "Novare Mall, Sangotedo",
      closes_at: "21:00",
      sort_order: 1,
      items: [
        ["Original Recipe 2pc + chips", 6500],
        ["8pc bucket", 18000],
        ["Wrap meal", 5500],
        ["Refuel Meal", 7000],
        ["Zinger burger meal", 8000],
      ] as const,
    },
    {
      name: "Domino's Pizza",
      address: "KM 34 Lekki-Epe Expy, Emperor Estate",
      closes_at: "22:00",
      sort_order: 2,
      items: [
        ["Medium pepperoni", 11000],
        ["Medium BBQ chicken", 12000],
        ["Large meat lovers", 17500],
        ["Chicken wings (6)", 6500],
        ["Garlic bread", 3000],
      ] as const,
    },
  ];

  for (const place of launch) {
    const { data: restaurant } = await db()
      .from("restaurants")
      .insert({
        name: place.name,
        address: place.address,
        closes_at: place.closes_at,
        active: true,
        sort_order: place.sort_order,
      })
      .select("id")
      .single();
    if (!restaurant) continue;

    await db().from("menu_items").insert(
      place.items.map(([name, price], index) => ({
        restaurant_id: restaurant.id,
        name,
        price_food: price,
        sort_order: index + 1,
      }))
    );
  }
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * A run on any day, at any cut-off. The automatic Friday batches cover the
 * usual week; this is for everything else, including exam-week late runs.
 */
export async function createBatch(form: FormData): Promise<void> {
  await assertAdmin();

  const runDate = String(form.get("run_date") ?? "").trim();
  const slot = String(form.get("slot") ?? "night");
  const time = String(form.get("cut_off_time") ?? "").trim();
  if (!runDate || !time) return;

  const [hour, minute] = time.split(":").map(Number);
  if (!Number.isFinite(hour) || !Number.isFinite(minute)) return;

  await db()
    .from("batches")
    .upsert(
      {
        run_date: runDate,
        slot,
        cut_off_at: lagosInstant(runDate, hour, minute),
        delivery_window_text:
          String(form.get("delivery_window_text") ?? "").trim() ||
          (await deliveryWindows())[slot as BatchSlot],
        status: "open",
        stage: "ordering",
      },
      { onConflict: "run_date,slot" }
    );

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function addCategory(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("menu_categories").insert({
    restaurant_id: String(form.get("restaurant_id")),
    name,
    sort_order: Number(form.get("sort_order") ?? 100),
  });
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function deleteCategory(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("menu_categories").delete().eq("id", String(form.get("category_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** A choice on an item: Size, Flavour, Extras. */
export async function addOptionGroup(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("item_option_groups").insert({
    menu_item_id: String(form.get("item_id")),
    name,
    required: form.get("required") === "on",
    max_select: Math.max(1, Number(form.get("max_select") ?? 1)),
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function deleteOptionGroup(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("item_option_groups").delete().eq("id", String(form.get("group_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function addOption(form: FormData): Promise<void> {
  await assertAdmin();
  const name = String(form.get("name") ?? "").trim();
  if (!name) return;

  await db().from("item_options").insert({
    group_id: String(form.get("group_id")),
    name,
    price_delta: Math.round(Number(form.get("price_delta") ?? 0)) || 0,
    sort_order: 100,
  });
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function updateOption(form: FormData): Promise<void> {
  await assertAdmin();
  await db()
    .from("item_options")
    .update({
      name: String(form.get("name") ?? "").trim() || undefined,
      price_delta: Math.round(Number(form.get("price_delta") ?? 0)) || 0,
      available: form.get("available") === "on",
    })
    .eq("id", String(form.get("option_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function deleteOption(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("item_options").delete().eq("id", String(form.get("option_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

export async function deleteMenuItem(form: FormData): Promise<void> {
  await assertAdmin();
  await db().from("menu_items").delete().eq("id", String(form.get("item_id")));
  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * A whole menu in one paste. One item per line:
 *
 *   Category | Item name | Price | Description
 *
 * Category and description may be left out. Categories are created as they are
 * met, so a price list copied off a menu goes in without fifty separate forms.
 */
export async function importMenu(form: FormData): Promise<void> {
  await assertAdmin();

  const restaurantId = String(form.get("restaurant_id"));
  const text = String(form.get("menu_text") ?? "");
  if (!restaurantId || !text.trim()) return;

  const parsed = parseMenuText(text);
  if (parsed.length === 0) return;

  const { data: existing } = await db()
    .from("menu_categories")
    .select("id, name")
    .eq("restaurant_id", restaurantId);

  const categories = new Map(
    ((existing ?? []) as { id: string; name: string }[]).map((c) => [
      c.name.toLowerCase(),
      c.id,
    ])
  );

  let sort = 100;

  for (const item of parsed) {
    let categoryId: string | null = null;

    if (item.category) {
      const key = item.category.toLowerCase();
      if (!categories.has(key)) {
        const { data: created } = await db()
          .from("menu_categories")
          .insert({ restaurant_id: restaurantId, name: item.category, sort_order: sort })
          .select("id")
          .single();
        if (created) categories.set(key, created.id as string);
      }
      categoryId = categories.get(key) ?? null;
    }

    await db().from("menu_items").insert({
      restaurant_id: restaurantId,
      category_id: categoryId,
      name: item.name,
      price_food: item.price,
      description: item.description,
      // Unpriced or sold-out items are created but hidden, so nobody can order
      // a ₦0 pizza or something the shop has run out of.
      available: item.available && item.price > 0,
      sort_order: sort,
    });
    sort += 1;
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * The same choice group on every item in a category. Fifteen pizzas each
 * needing Small, Medium and Large is not fifteen forms.
 */
export async function applyGroupToCategory(form: FormData): Promise<void> {
  await assertAdmin();

  const categoryId = String(form.get("category_id"));
  const groupName = String(form.get("group_name") ?? "").trim();
  const raw = String(form.get("options") ?? "").trim();
  if (!categoryId || !groupName || !raw) return;

  // "Small, Medium +2000, Large +5500"
  const options = raw
    .split(/[,\n]/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part, index) => {
      const match = part.match(/^(.*?)(?:\s*([+-]\s*[\d,.]+))?$/);
      const name = (match?.[1] ?? part).trim();
      const delta = match?.[2]
        ? Math.round(Number(match[2].replace(/[^\d.-]/g, "")))
        : 0;
      return { name, delta: Number.isFinite(delta) ? delta : 0, sort: index + 1 };
    })
    .filter((option) => option.name);

  const { data: items } = await db()
    .from("menu_items")
    .select("id")
    .eq("category_id", categoryId);

  for (const item of (items ?? []) as { id: string }[]) {
    const { data: existing } = await db()
      .from("item_option_groups")
      .select("id")
      .eq("menu_item_id", item.id)
      .eq("name", groupName)
      .maybeSingle();
    if (existing) continue;

    const { data: group } = await db()
      .from("item_option_groups")
      .insert({
        menu_item_id: item.id,
        name: groupName,
        required: form.get("required") === "on",
        max_select: Math.max(1, Number(form.get("max_select") ?? 1)),
        sort_order: 1,
      })
      .select("id")
      .single();
    if (!group) continue;

    await db().from("item_options").insert(
      options.map((option) => ({
        group_id: group.id,
        name: option.name,
        price_delta: option.delta,
        sort_order: option.sort,
      }))
    );
  }

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** One tap on and off, for the times a branch has run out mid-week. */
export async function toggleItemAvailable(form: FormData): Promise<void> {
  await assertAdmin();

  await db()
    .from("menu_items")
    .update({ available: form.get("available") === "true" })
    .eq("id", String(form.get("item_id")));

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/**
 * Move one row up or down a list that the customer sees.
 *
 * The whole list is renumbered rather than the two rows swapped, because a
 * seeded list is full of ties: everything arrives at sort_order 100 and a
 * swap between two hundreds changes nothing. Renumbering also means the
 * order you see in admin is the order that gets saved.
 */
async function shuffle(
  table: "restaurants" | "slides",
  id: string,
  direction: "up" | "down"
): Promise<void> {
  // Restaurants have no created_at, so ties break on the name instead.
  const tiebreak = table === "slides" ? "created_at" : "name";
  const { data } = await db()
    .from(table)
    .select("id")
    .order("sort_order")
    .order(tiebreak);

  const list = (data ?? []) as { id: string }[];
  const at = list.findIndex((row) => row.id === id);
  if (at < 0) return;

  const to = direction === "up" ? at - 1 : at + 1;
  if (to < 0 || to >= list.length) return;

  [list[at], list[to]] = [list[to], list[at]];

  await Promise.all(
    list.map((row, index) =>
      db().from(table).update({ sort_order: index + 1 }).eq("id", row.id)
    )
  );

  revalidatePath("/admin", "layout");
  revalidatePath("/", "layout");
}

/** Reorder the restaurant list, which is the order on the home page. */
export async function moveRestaurant(form: FormData): Promise<void> {
  await assertAdmin();
  await shuffle(
    "restaurants",
    String(form.get("restaurant_id")),
    form.get("direction") === "up" ? "up" : "down"
  );
}

/** Reorder the home page slider. */
export async function moveSlide(form: FormData): Promise<void> {
  await assertAdmin();
  await shuffle(
    "slides",
    String(form.get("slide_id")),
    form.get("direction") === "up" ? "up" : "down"
  );
}
