import type { BatchSlot } from "./config";
import type { BatchStage } from "./stages";

export type Restaurant = {
  id: string;
  name: string;
  /** The readable half of a link: /r/dominos-pizza. Empty on a database that
   *  has not had the migration run, which is why nothing depends on it. */
  slug?: string | null;
  address: string;
  closes_at: string;
  active: boolean;
  sort_order: number;
  logo_url: string;
  banner_url: string;
  brand_hex: string;
};

export type MenuCategory = {
  id: string;
  restaurant_id: string;
  name: string;
  sort_order: number;
};

export type OptionGroup = {
  id: string;
  menu_item_id: string;
  name: string;
  required: boolean;
  max_select: number;
  sort_order: number;
};

export type ItemOption = {
  id: string;
  group_id: string;
  name: string;
  price_delta: number;
  available: boolean;
  sort_order: number;
};

export type MenuItem = {
  id: string;
  restaurant_id: string;
  name: string;
  price_food: number;
  available: boolean;
  sort_order: number;
  image_url: string;
  description: string;
  category_id: string | null;
};

export type BatchStatus = "open" | "closed" | "delivered" | "cancelled";

export type Batch = {
  id: string;
  run_date: string;
  slot: BatchSlot;
  cut_off_at: string;
  delivery_window_text: string;
  status: BatchStatus;
  capacity: number | null;
  flash_fee: number | null;
  flash_fee_reason: string;
  stage: BatchStage;
  stage_updated_at: string;
  /** A scheduled run everybody shares, or one person's same day delivery. */
  kind: "run" | "same_day";
  /** The time asked for. Only ever set on a same day delivery. */
  deliver_at: string | null;
  /** What the run cost to make, typed in once it is done. */
  fuel_cost: number;
  /** What the food actually cost at the counters, when that is not the menu
   *  price. Zero means the menu prices stand. */
  food_spend: number;
  driver_cost: number;
  other_cost: number;
  cost_note: string;
};

export type OrderStatus = "pending" | "paid" | "refunded" | "delivered";

export type Order = {
  id: string;
  /** The short number on the run sheet and in messages: #1042. */
  order_no: number | null;
  batch_id: string;
  customer_phone: string;
  customer_name: string;
  hostel: string;
  subtotal_food: number;
  fee: number;
  discount: number;
  total: number;
  payment_ref: string | null;
  paid_at: string | null;
  /** The discount code used, if one was. */
  coupon_code: string | null;
  /** The order whose join link they opened, when they joined a delivery. */
  shared_with: string | null;
  /** Set when this person said they had finished adding to a shared delivery. */
  done_at: string | null;
  /** One to five, once the food has arrived and they have said. */
  rating: number | null;
  feedback: string;
  rated_at: string | null;
  status: OrderStatus;
  created_at: string;
  group_id: string | null;
  for_name: string | null;
  refund_owed: number;
  payment_method: "transfer" | "card";
  /** A card link generated by hand, kept so it can be sent again. */
  payment_link: string | null;
  /** What the customer asked for, in their words. */
  customer_note: string;
  /** What the admin wants remembered about this order. Never shown to them. */
  admin_note: string;
};

export type OrderItem = {
  id: string;
  order_id: string;
  menu_item_id: string;
  qty: number;
  unit_price_at_order: number;
  for_name: string | null;
};

export type OrderGroup = {
  id: string;
  batch_id: string;
  leader_phone: string;
  leader_name: string;
  hostel: string;
  mode: GroupMode;
  collect_mode: "leader" | "each";
  /** Set only on a shared delivery: when it stops taking people, and when it
   *  actually stopped. An ordinary group order has neither. */
  closes_at: string | null;
  closed_at: string | null;
  /** Who pays for everybody, when the group decided one person does. */
  payer_phone: string | null;
  /** The token from the link this party was started with. */
  party_token: string | null;
  created_at: string;
};

export type Promoter = {
  code: string;
  /** Their own four-digit sign-in, given out on WhatsApp. */
  pin?: string;
  name: string;
  phone: string;
  rate: number;
  active: boolean;
  /** Where their money goes. They keep it up to date themselves. */
  bank_name: string;
  bank_account_name: string;
  bank_account_number: string;
};

/** What the cart posts to the server. Prices are never trusted from here. */
export type CartLine = {
  menu_item_id: string;
  qty: number;
  /** Chosen size, flavour and extras. Priced on the server, never here. */
  option_ids?: string[];
  /** Whose food this is, in a group cart. Null for a single-person order. */
  for_name?: string | null;
};

export type GroupMode = "one_payer" | "split";

export type Hostel = {
  id: string;
  name: string;
  note: string;
  active: boolean;
  sort_order: number;
};
